# =============================================================================
# Script: 1_3_Process_Ig_Translocation_Info.R
# 
# Script purpose:
#   This script ingests immunoglobulin (Ig) translocation calls generated by
#   the Ig_caller from cfWGS data, cleans and structures them for downstream
#   integration and figure generation. It performs the following steps:
#     1. Reads all “*_filtered.tsv” outputs in cfWGS_res_dir and extracts only
#        the lines containing “Translocation”.
#     2. Parses each line into columns: breakpoint1/2 (chr:pos), strand,
#        gene1/gene2, IGCaller_Score, Mappability_Issue, plus sample IDs.
#     3. (Optional) Builds a MAVIS‐compatible input table of breakpoints.
#     4. Loads cytoband definitions from “Oct 2024 data/cytoBand.txt” and
#        maps each breakpoint coordinate to its cytoband.
#     5. Flags potential myeloma translocations (t(11;14), t(4;14), t(14;16),
#        t(14;20), t(6;14), t(8;14)) and filters for score/mappability thresholds.
#     6. Annotates each call with:
#         • Common_MM_translocation (1/0 for canonical IGH‐X fusions)
#         • Potential_MM_translocation (1/0 for any IGH‐X event)
#         • Recurrent_TRA (“Yes”/“No” if in chr14q32.33 plus recurrent partner)
#     7. Standardizes “gene1/gene2” into IG_gene and Other_gene, then removes
#        ENCODE blacklist overlaps via GenomicRanges.
#     8. Summarizes counts of patients per gene pair and generates barplots
#        and histograms of fusion frequencies.
# 
# Inputs:
#   • cfWGS_res_dir      = "Oct 2024 data/Ig_caller/"      # Ig_caller “*_filtered.tsv” files
#   • Cytoband table     = "Oct 2024 data/cytoBand.txt"
#   • ENCODE blacklist   = "hg38-blacklist.v2.bed"
#   • Clinical metadata  = combined_clinical_data_updated_Feb5_2025.csv
#     This is the historical base table used literally by the script, not the
#     April 2025 table written by 1_0. helpers.R may append revision metadata.
#   • Cohort assignments = validated final 71-patient table loaded by helpers.R
#   • IGV BAM inventory  = IG_Mini_Bams.csv
#   • Shared helper       = Scripts_2025/Final_Scripts/helpers.R
#   • Historical reviewed calls = Jan2025_exported_data/
#       Ig_caller_df_cfWGS_filtered_aggressive2_iGV_check.xlsm
#   • Revision reviewed calls = Scripts_2025/Final_Scripts/data/curation/
#       igcaller_revision_2026_igv_review.tsv
#   • Optional Spring 2026 metadata and IgCaller outputs under
#       Data_Spring_2026_Revisions/
#
# Analysis units:
#   Automated tables contain one candidate breakpoint pair per sample. The final
#   downstream matrix contains one row per sample with at least one manually
#   confirmed canonical call; absence of a row is not independently proof of a
#   negative call unless downstream code joins to the full sample inventory and
#   explicitly replaces missing feature values with zero.
#   If a BAM has multiple confirmed canonical calls, the current matrix-building
#   step retains only its highest-IGCaller-score row.
#
# Manual checkpoint:
#   This is not a fully unattended workflow. Candidate calls are exported for
#   IGV review, and only rows marked `Looks_real == 1` in either the historical
#   workbook or the separate revision review table enter the final feature
#   matrix. Fractional `Looks_real` values remain review evidence but are not
#   promoted to confirmed translocation calls.
# 
# Active downstream outputs:
#   • Jan2025_exported_data/translocation_data_cytoband_updated.rds
#   • Jan2025_exported_data/translocation_data_cytoband_updated.txt
#     These IGV-confirmed cytoband-level translocation feature matrices are
#     consumed by downstream feature-integration, heatmap, and concordance
#     scripts.
#
# Support-only outputs:
#   • Output_tables_2025/translocation_processing_support/*.rds
#   • Output_tables_2025/translocation_processing_support/
#       pre_igv_feature_matrices/*.{rds,txt}
#   • Output_tables_2025/translocation_processing_support/
#       spring2026_IgCaller_common_MM_translocation_candidates_for_IGV_review.csv
#   • Output_figures_2025/translocation_processing_support/*.png
#   • IGV_screenshotter/Bed_files_translocations_cytoband/*.bed
#   • IGV_screenshotter/Bed_files_translocations_cytoband_breakpoint_2/*.bed
#     These are parsing caches, pre-IGV automated feature matrices, and QC plots.
#     They are not final manuscript figures or tables.
#
# Curation output:
#   • Jan2025_exported_data/Ig_caller_df_cfWGS_filtered_aggressive2_iGV_check.txt
#     Candidate common-MM translocation calls for manual IGV review. The final
#     feature matrix is built from the reviewed workbook with Looks_real == 1.
# 
# Dependencies:
#   ChromHeatMap, tidyverse, stringr, readxl, reshape2, ComplexHeatmap,
#   RColorBrewer, circlize, GenomicRanges, pbapply, and stringdist. All packages
#   loaded below must be installed, including those used only in legacy/support
#   sections.
# 
# How to run from the repository root:
#   Rscript 1_3_Process_Ig_Translocation_Info.R
#
# Manuscript outputs created/updated:
#   - None directly. This upstream script processes Ig-caller translocation
#     calls for WGS feature integration, baseline heatmaps, and FISH/WGS
#     concordance analyses.
#
# Author: Dory Abelman
# Date:   2025-05-26
# =============================================================================
# Pipeline status:
#   Active upstream dependency. This script does not directly create a named
#   final manuscript figure/table. It creates the IGV-confirmed translocation
#   feature matrix consumed by later manuscript-output scripts.
#



#### Load Libraries 
library(ChromHeatMap)
data("cytobands")
library(tidyverse)
library(stringr)
library(readxl)
library(reshape2)
library(ComplexHeatmap)
library(RColorBrewer)
library(circlize)
library(GenomicRanges)
library(pbapply)

.helpers_path <- file.path("Scripts_2025", "Final_Scripts", "helpers.R")
if (!file.exists(.helpers_path)) {
  .helpers_path <- "helpers.R"
}
source(.helpers_path)
rm(.helpers_path)

support_table_dir <- file.path("Output_tables_2025", "translocation_processing_support")
support_figure_dir <- file.path("Output_figures_2025", "translocation_processing_support")
dir.create(support_table_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(support_figure_dir, recursive = TRUE, showWarnings = FALSE)

support_path <- function(filename) file.path(support_table_dir, filename)

write_support_rds <- function(x, filename) {
  path <- support_path(filename)
  saveRDS(x, file = path)
  message("Support RDS written: ", path)
  invisible(path)
}

support_png <- function(filename) file.path(support_figure_dir, filename)

first_existing <- function(candidates, label) {
  hit <- candidates[file.exists(candidates)][1]
  if (is.na(hit)) {
    stop(
      "Could not find ", label, ". Checked:\n  ",
      paste(candidates, collapse = "\n  "),
      call. = FALSE
    )
  }
  hit
}


### Add clinical metadata for sample/patient annotation.
# Spring 2026 revision samples are independent test-cohort additions and are
# loaded through the same metadata projection used by mutation, CNA, MRDetect,
# and fragmentomics scripts. The final confirmed translocation matrix still
# requires IGV review (Looks_real == 1) before new calls are promoted.
metada_df_mutation_comparison <- read_combined_clinical_metadata_with_revision(
  "combined_clinical_data_updated_Feb5_2025.csv"
)
# Use the final 71-patient cohort here. The older cohort file does not contain
# the new revision patients, so using it would leave their IgCaller calls out of
# the IGV review table.
cohort_df <- load_final_cohort_assignment(required = TRUE, validate_current = TRUE)

# Add a Tumor_Sample_Barcode column to metada_df_mutation_comparison
metada_df_mutation_comparison <- metada_df_mutation_comparison %>%
  mutate(Tumor_Sample_Barcode = Bam %>%
           # Remove _PG or _WG
           str_remove_all("_PG|_WG") %>%
           # Remove anything after ".filter", ".ded", or ".recalibrate"
           str_replace_all("\\.filter.*|\\.ded.*|\\.recalibrate.*", ""))

metada_df_mutation_comparison <- metada_df_mutation_comparison %>%
  mutate(Bam_clean_tmp = gsub(".bam$", "", Bam))  # Remove the '.bam' suffix


### Load raw files
cfWGS_res_dir <- "Oct 2024 data/Ig_caller/"

cfWGS_res_filtered_f <- list.files(cfWGS_res_dir,
                                   pattern = "_filtered.tsv",  
                                   recursive = T,
                                   full.names = T)
cfWGS_res_filtered_f <- unique(c(
  cfWGS_res_filtered_f,
  # Append Spring 2026 IgCaller filtered outputs from the revision data root.
  # These rows are parsed and exported for review, but final translocation
  # feature calls are still gated by manual IGV review below.
  spring2026_revision_files("Ig_caller_all_filtered_outputs", "_filtered[.]tsv$")
))

cfWGS_res_filtered <- data.frame()

if (!length(cfWGS_res_filtered_f)) {
  cached_igcaller_path <- first_existing(
    c(
      support_path("Oct_2024_Ig_caller_MM_translocations_all.rds"),
      "Oct_2024_Ig_caller_MM_translocations_all.rds"
    ),
    "parsed Ig_caller cache"
  )
  message(
    "No raw Ig_caller *_filtered.tsv files found in ", cfWGS_res_dir,
    "; using cached parsed Ig_caller object: ", cached_igcaller_path
  )
  cfWGS_res_filtered <- readRDS(cached_igcaller_path)
} else {
for(f in cfWGS_res_filtered_f){
  
  lns <- readLines(f)
  # Keep only lines describing a translocation event; other event types
  # (Deletion, Insertion, Inversion) reported by Ig_caller are discarded here
  # because this study focuses exclusively on IGH/IGL/IGK translocations.
  lns <- subset(lns, grepl("Translocation",lns))
  # Normalise the raw Ig_caller output into a tab-delimited form readable by
  # read.table().  Each gsub() step covers one formatting convention:
  #   gsub 1: strip square brackets wrapping breakpoint coordinates.
  #   gsub 2: replace ";chr" (second breakpoint separator) with a tab so each
  #           breakpoint becomes its own field.
  #   gsub 3-5: split "chr:pos strand" into two tab-separated fields.
  lns <-  gsub("\\[|\\]", "", lns)
  lns <-  gsub(";chr", "\tchr", lns)
  lns <-  gsub(" - ", "\t", lns)
  lns <-  gsub(":\\+", "\t\\+", lns)
  lns <-  gsub(":-", "\t-", lns)
  
  if(length(lns)>0){
    tmp_res <- read.table(text = lns)
    
    # Columns 5,6,7,8 = breakpoint1, breakpoint1_strand, breakpoint2,
    # breakpoint2_strand; cols 9,10 = gene1, gene2; col 12 = IGCaller_Score;
    # col 15 = Mappability_Issue.  These positions are fixed by the Ig_caller
    # v2 output format; if the pipeline version changes, verify the column
    # order by inspecting a raw *_filtered.tsv before running this script.
    tmp_res <- tmp_res[,c(5,6,7,8,9,10,12,15)]
    colnames(tmp_res) <- c("breakpoint1", "breakpoint1_strand", 
                           "breakpoint2", "breakpoint2_strand",
                           "gene1", "gene2","IGCaller_Score","Mappability_Issue")
    
    tmp_res$Bam_File <- gsub("_output_filtered.tsv",".bam",basename(f))
    
    tmp_res$Sample <- gsub(".sorted_indelrealigned.all.unique.dcs.sorted_output_filtered.tsv","",basename(f))
    
    ## output mavis compatible input
    # The MAVIS block below constructs a structural-variant input table for the
    # MAVIS validation and annotation pipeline.  The write.table() call is
    # commented out because MAVIS validation was not performed in this instance. The
    # mavis_input data.frame is retained for reference if re-validation is needed.
    # Odd-indexed elements of sep_breakpoint* are chromosomes; even-indexed are
    # positions (strsplit produces chr, pos alternately across all rows at once).
    sep_breakpoint1 <- unlist(strsplit(tmp_res$breakpoint1,":"))
    sep_breakpoint2 <- unlist(strsplit(tmp_res$breakpoint2,":"))
    
    mavis_input <- data.frame(break1_chromosome = sep_breakpoint1[seq(1,length(sep_breakpoint1),2)],
                              break1_position_start = sep_breakpoint1[seq(2,length(sep_breakpoint1),2)],
                              break1_position_end = sep_breakpoint1[seq(2,length(sep_breakpoint1),2)],
                              break2_chromosome = sep_breakpoint2[seq(1,length(sep_breakpoint2),2)],
                              break2_position_start  = sep_breakpoint2[seq(2,length(sep_breakpoint2),2)],
                              break2_position_end  = sep_breakpoint2[seq(2,length(sep_breakpoint2),2)])
    
    #  write.table(mavis_input, row.names = F, sep = "\t",quote = F,
    #               file = gsub(".tsv.txt","_mavis_input.txt",f))
    
    if(f == cfWGS_res_filtered_f[1]){
      cfWGS_res_filtered <- tmp_res
    } else {
      cfWGS_res_filtered <- rbind(cfWGS_res_filtered,
                                  tmp_res)
      
    }
  }
}
}

## Add cytobands

#cb_frame <- cytobands$`Homo sapiens`
cb_frame <- read_tsv("Oct 2024 data/cytoBand.txt")
colnames(cb_frame) <- c("chr", "start", "end", "band", "stain")

sep_breakpoint1 <- unlist(strsplit(cfWGS_res_filtered$breakpoint1,":"))
sep_breakpoint2 <- unlist(strsplit(cfWGS_res_filtered$breakpoint2,":"))

cfWGS_res_filtered$break1_chromosome <- sep_breakpoint1[seq(1,length(sep_breakpoint1),2)]
cfWGS_res_filtered$break1_position_start  <- sep_breakpoint1[seq(2,length(sep_breakpoint1),2)]
cfWGS_res_filtered$break1_position_end <- cfWGS_res_filtered$break1_position_start

cfWGS_res_filtered$break2_chromosome <- sep_breakpoint2[seq(1,length(sep_breakpoint2),2)]
cfWGS_res_filtered$break2_position_start  <- sep_breakpoint2[seq(2,length(sep_breakpoint2),2)]
cfWGS_res_filtered$break2_position_end <- cfWGS_res_filtered$break2_position_start

cfWGS_res_filtered$break1_cytoband <- NA
cfWGS_res_filtered$break2_cytoband <- NA

write_support_rds(cfWGS_res_filtered, "Oct_2024_Ig_caller_MM_translocations_all.rds")

## Filter to MM translocations
# First-pass chromosome-pair filter: retains any event involving chr14 paired
# with chr4, chr6, chr8, chr11, chr16, or chr20, regardless of gene annotation.
# This is intentionally broad; score/mappability filters and gene-level rules
# below will further prioritise calls.  Both orientations (break1/break2 order)
# are checked because Ig_caller does not guarantee a canonical strand order.
cfWGS_res_filtered <- cfWGS_res_filtered %>%
  mutate(Potential_MM_translocation = ifelse(
    (break1_chromosome == "chr11" & break2_chromosome == "chr14") |  # t(11;14)
      (break1_chromosome == "chr14" & break2_chromosome == "chr11") |
      (break1_chromosome == "chr4" & break2_chromosome == "chr14") |   # t(4;14)
      (break1_chromosome == "chr14" & break2_chromosome == "chr4") |
      (break1_chromosome == "chr14" & break2_chromosome == "chr16") |  # t(14;16)
      (break1_chromosome == "chr16" & break2_chromosome == "chr14") |
      (break1_chromosome == "chr14" & break2_chromosome == "chr20") |  # t(14;20)
      (break1_chromosome == "chr20" & break2_chromosome == "chr14") |
      (break1_chromosome == "chr6" & break2_chromosome == "chr14") |   # t(6;14)
      (break1_chromosome == "chr14" & break2_chromosome == "chr6") |
      (break1_chromosome == "chr8" & break2_chromosome == "chr14") |   # t(8;14)
      (break1_chromosome == "chr14" & break2_chromosome == "chr8"),
    1, 0))

# Filter rows where Potential_MM_translocation == 1 (only rows with relevant translocations)
cfWGS_res_filtered <- cfWGS_res_filtered %>%
  filter(Potential_MM_translocation == 1)

# and remove rows where IGCaller_Score <= 20 when Mappability_Issue is not "none"
# Rationale: a low-confidence score (<= 20) combined with a mappability warning
# indicates the breakpoint overlaps a repetitive or low-complexity region and
# the call is unreliable.  Rows with no mappability issue are retained at this
# step because even low-scoring calls in clean regions will be re-evaluated by
# the gene-level and ENCODE-blacklist filters applied later in the script.
cfWGS_res_filtered <- cfWGS_res_filtered %>%
  filter(!(IGCaller_Score <= 20 & Mappability_Issue != "none"))

library(pbapply)  # For progress bar

# Function to match cytobands for each breakpoint - much faster than original 
# match_cytoband_fast() performs a vectorised filter on the cytoband reference
# table (hg38 cytoBand.txt from UCSC) instead of looping over every row.
# It returns a combined string e.g. "chr14q32.33" used downstream to identify
# the IGH locus and canonical MM translocation partner bands.
# pbapply::pbsapply() wraps the row-wise apply with a progress bar so long
# batches (>500 calls) don't appear to hang.
match_cytoband_fast <- function(chromosome, position_start, cb_frame) {
  # Vectorized filtering of the cytoband dataframe
  matched_cb <- cb_frame %>%
    filter(chr == chromosome & start <= as.numeric(position_start) & end >= as.numeric(position_start)) %>%
    slice(1)  # Take the first match
  
  # Return cytoband if a match is found, else NA
  if (nrow(matched_cb) > 0) {
    return(paste0(matched_cb$chr, matched_cb$band))
  } else {
    return(NA)
  }
}

# Apply match_cytoband_fast function with progress bar using pbapply
cfWGS_res_filtered <- cfWGS_res_filtered %>%
  mutate(
    break1_cytoband = pbapply::pbsapply(1:nrow(cfWGS_res_filtered), function(i) {
      match_cytoband_fast(cfWGS_res_filtered$break1_chromosome[i], cfWGS_res_filtered$break1_position_start[i], cb_frame)
    }),
    break2_cytoband = pbapply::pbsapply(1:nrow(cfWGS_res_filtered), function(i) {
      match_cytoband_fast(cfWGS_res_filtered$break2_chromosome[i], cfWGS_res_filtered$break2_position_start[i], cb_frame)
    })
  )

write_support_rds(cfWGS_res_filtered, "Oct_2024_Ig_caller_MM_translocations_with_cytoband.rds")


cfWGS_res_filtered$Recurrent_TRA <- "No"

# Flag events where one breakpoint is chr14q32.33 (the IGH locus) and the
# other is one of the three most common MM partner cytobands:
#   11q13 -> CCND1 (t(11;14))
#   4p16  -> FGFR3/NSD2 (t(4;14))
#   16q23 -> MAF (t(14;16))
# Both orientations (break1 vs break2 being the IGH side) are checked.
cfWGS_res_filtered$Recurrent_TRA[grepl("11q13|4p16|16q23",
                                       cfWGS_res_filtered$break1_cytoband) &
                                   cfWGS_res_filtered$break2_cytoband == "chr14q32.33"] <- "Yes"

cfWGS_res_filtered$Recurrent_TRA[grepl("11q13|4p16|16q23",
                                       cfWGS_res_filtered$break2_cytoband) &
                                   cfWGS_res_filtered$break1_cytoband == "chr14q32.33"] <- "Yes"

cfWGS_res_filtered$Sample <- gsub(".fastq.gz", "", cfWGS_res_filtered$Sample)

cfWGS_res_filtered$trans_ID <- paste(cfWGS_res_filtered$Sample,
                                     cfWGS_res_filtered$break1_cytoband,
                                     cfWGS_res_filtered$break2_cytoband)


Ig_caller_df_cfWGS_filtered <- cfWGS_res_filtered
## Create a column for if a MM translocation found 

# Replace NAs
Ig_caller_df_cfWGS_filtered$break2_cytoband <- ifelse(is.na(Ig_caller_df_cfWGS_filtered$break2_cytoband), Ig_caller_df_cfWGS_filtered$break2_chromosome, Ig_caller_df_cfWGS_filtered$break2_cytoband)
Ig_caller_df_cfWGS_filtered$break1_cytoband <- ifelse(is.na(Ig_caller_df_cfWGS_filtered$break1_cytoband), Ig_caller_df_cfWGS_filtered$break1_chromosome, Ig_caller_df_cfWGS_filtered$break1_cytoband)

# First create translocation column: 
Ig_caller_df_cfWGS_filtered$Translocation <- paste(Ig_caller_df_cfWGS_filtered$break1_cytoband, Ig_caller_df_cfWGS_filtered$break2_cytoband, sep = "_")

# Then sort it 
# Alphabetically sorting the two cytoband components ("chr11q13.3" and
# "chr14q32.33" -> stored as "chr11q13.3_chr14q32.33") normalises the
# translocation string regardless of which breakpoint the caller places first.
# This canonical form is then matched against the myeloma_translocations list
# defined below.  Without this step, the same event can appear twice under
# different orientations and fail the %in% lookup.
# Function to sort the elements in the translocation string
sort_translocation <- function(translocation) {
  parts <- strsplit(translocation, "_")[[1]]
  sorted_parts <- sort(parts)
  return(paste(sorted_parts, collapse = "_"))
}


# Apply the function to the 'Translocation' column and create the new 'sorted_translocation' column
Ig_caller_df_cfWGS_filtered$Sorted_translocation <- apply(Ig_caller_df_cfWGS_filtered["Translocation"], 1, function(x) sort_translocation(x))

# Now see if a myeloma translocation was found 

## These are the most common
# This list defines the eight canonical myeloma IGH translocations at cytoband
# resolution after sort_translocation() normalisation.  Each entry maps to the
# established WHO/IMWG cytogenetic subgroup.  Calls matching this list are
# labelled Common_MM_translocation == 1 and carry a lower score threshold in
# the aggressive filter below, reflecting greater prior probability of being real.
myeloma_translocations <- c(
  "chr11q13.3_chr14q32.33",  # t(11;14) involving CCND1 and IGH
  "chr14q32.33_chr16q23.2",  # t(14;16) involving MAF and IGH
  "chr14q32.33_chr20q13.33", # t(14;20) involving MAFB and IGH
  "chr11q13.2_chr14q32.33",  # t(11;14) variation
  "chr14q32.33_chr4p16.3",   # t(4;14) involving FGFR3/MMSET and IGH
  "chr14q32.33_chr6q21",     # t(6;14) involving CCND3 and IGH
  "chr14q32.33_chr8q24.21",  # t(8;14) involving MYC and IGH
  "chr14q32.33_chr6p21"      # t(6;14) involving CCND3 and IGH (variant of Cyclin D deregulation)
)

Ig_caller_df_cfWGS_filtered <- Ig_caller_df_cfWGS_filtered %>%
  mutate(
    Common_MM_translocation = if_else(Sorted_translocation %in% myeloma_translocations, 1, 0)
  )

## These are other potential ones 
# Add the potential_MM_translocation column
Ig_caller_df_cfWGS_filtered <- Ig_caller_df_cfWGS_filtered %>%
  mutate(Potential_MM_translocation = ifelse(
    (break1_chromosome == "chr11" & break2_chromosome == "chr14") |  # t(11;14)
      (break1_chromosome == "chr14" & break2_chromosome == "chr11") |
      (break1_chromosome == "chr4" & break2_chromosome == "chr14") |   # t(4;14)
      (break1_chromosome == "chr14" & break2_chromosome == "chr4") |
      (break1_chromosome == "chr14" & break2_chromosome == "chr16") |  # t(14;16)
      (break1_chromosome == "chr16" & break2_chromosome == "chr14") |
      (break1_chromosome == "chr14" & break2_chromosome == "chr20") |  # t(14;20)
      (break1_chromosome == "chr20" & break2_chromosome == "chr14") |
      (break1_chromosome == "chr6" & break2_chromosome == "chr14") |   # t(6;14)
      (break1_chromosome == "chr14" & break2_chromosome == "chr6") |
      (break1_chromosome == "chr8" & break2_chromosome == "chr14") |   # t(8;14)
      (break1_chromosome == "chr14" & break2_chromosome == "chr8"),
    1, 0))


## Add patient 
Ig_caller_df_cfWGS_filtered <- left_join(Ig_caller_df_cfWGS_filtered, metada_df_mutation_comparison, by = c("Bam_File" = "Bam"))

## Export what have so far 
# Save the dataframe as an RDS file
write_support_rds(Ig_caller_df_cfWGS_filtered, "Ig_caller_df_cfWGS_filtered_MM_only_filtered_Ig_caller_outputs_updated2.rds")


## Show recurrent mutations in genes 

Ig_caller_df_cfWGS_filtered <- Ig_caller_df_cfWGS_filtered %>%
  mutate(
    IG_gene = ifelse(!startsWith(gene1, "IG"), gene2, gene1),
    Other_gene = ifelse(!startsWith(gene1, "IG"), gene1, gene2)
  )


## get gene descriptions 

# Get list of all non IGH genes invovled with IG translocation and save to list
unique_genes <- Ig_caller_df_cfWGS_filtered %>%
  dplyr::select(gene1, gene2) %>% 
  unique()

# Reorder columns so Ig on first column 
unique_genes_swapped <- unique_genes %>%
  dplyr::mutate(
    gene1_temp = ifelse(!startsWith(gene1, "IG"), gene2, gene1),
    gene2_temp = ifelse(!startsWith(gene1, "IG"), gene1, gene2)
  ) %>%
  dplyr::select(IG_gene = gene1_temp, Other_gene = gene2_temp)

# List of relevant myeloma genes
relevant_myeloma_genes <- c(
  "FGFR3", "NSD2", "WHSC1",  # t(4;14)
  "CCND1", "CDK6", "BCL1",  # t(11;14)
  "MAF", "MAFB", "ITGB7",  # t(14;16), t(14;20)
  "MYC", "PVT1", "TMPO",  # t(8;14), MYC translocations
  "CCND3", "BMP6", "DUSP22",  # t(6;14)
  "IRF4", "CDKN2C",  # t(1;14)
  "BCL2", "BCL9"  # BCL2-related translocations
)

## First filter pass
# Four-tier confidence filter - rationale for each tier:
#
#   TIER 1 (Mappability_Issue != "none" AND score >= 100):
#     The breakpoint overlaps a low-mappability region (repetitive elements,
#     segmental duplications, etc.), so Ig_caller is less reliable.  The stricter
#     score threshold (100) compensates: only high-confidence calls are kept.
#
#   TIER 2 (Mappability_Issue == "none" AND score >= 50):
#     Both breakpoints are in uniquely mappable regions.  The standard threshold
#     (50) is applied; lower scores in clean regions still carry meaningful FP risk.
#
#   TIER 3 (Common_MM_translocation == 1 AND score > 15):
#     Canonical MM translocations (t(11;14), t(4;14), t(14;16), t(14;20), t(6;14),
#     t(8;14)) have very high prior probability of being real.  A lenient threshold
#     (> 15) is used here to ensure clinically relevant events are not missed when
#     sequencing depth is low.  These must still survive the ENCODE-blacklist filter.
#
#   TIER 4 (Other_gene %in% relevant_myeloma_genes):
#     If Ig_caller names a known MM driver (NSD2, CCND1, MAF, MAFB, etc.) as the
#     partner, retain regardless of score so established fusions are never silently
#     dropped by a numeric threshold.
Ig_caller_df_cfWGS_filtered <- Ig_caller_df_cfWGS_filtered %>%
  filter(
    # Keep if there is a mappability issue and score is at least 100
    (Mappability_Issue != "none" & IGCaller_Score >= 100) |
      # Or if there is no mappability issue and score is at least 50
      (Mappability_Issue == "none" & IGCaller_Score >= 50) |
      # Or if it is a common MM translocation and the score is over 15
      (Common_MM_translocation == 1 & IGCaller_Score > 15) |
      # Keep all translocations involving relevant myeloma genes, regardless of score
      (Other_gene %in% relevant_myeloma_genes)
  ) %>%
  filter(Potential_MM_translocation == 1 | Other_gene %in% relevant_myeloma_genes)

## Now remove encode blacklist 
# GRanges-based overlap removal: any call where either breakpoint falls within
# an ENCODE blacklist region (repetitive, high-signal, or assembly artefact
# regions in hg38-blacklist.v2.bed) is removed.  Both breakpoints are tested
# independently; if either overlaps the blacklist the entire row is discarded
# (all_overlap_indices is the union of both queryHits vectors).  The 'encode'
# subset is kept separately for audit purposes.
bed_file_encode <- read_tsv("hg38-blacklist.v2.bed")
colnames(bed_file_encode) <- c("chrom", "start", "stop", "description")

# Convert the bed file to a GRanges object
Ig_caller_df_cfWGS_filtered$break1_position_start <- as.numeric(Ig_caller_df_cfWGS_filtered$break1_position_start)
Ig_caller_df_cfWGS_filtered$break1_position_end <- as.numeric(Ig_caller_df_cfWGS_filtered$break1_position_end)
Ig_caller_df_cfWGS_filtered$break2_position_start <- as.numeric(Ig_caller_df_cfWGS_filtered$break2_position_start)
Ig_caller_df_cfWGS_filtered$break2_position_end <- as.numeric(Ig_caller_df_cfWGS_filtered$break2_position_end)

# Create GRanges objects for the filtered Ig caller data and the ENCODE bed file
Ig_caller_df_cfWGS_filtered_gr1 <- GRanges(
  Ig_caller_df_cfWGS_filtered$break1_chromosome,
  IRanges(Ig_caller_df_cfWGS_filtered$break1_position_start, Ig_caller_df_cfWGS_filtered$break1_position_end)
)

Ig_caller_df_cfWGS_filtered_gr2 <- GRanges(
  Ig_caller_df_cfWGS_filtered$break2_chromosome,
  IRanges(Ig_caller_df_cfWGS_filtered$break2_position_start, Ig_caller_df_cfWGS_filtered$break2_position_end)
)

bed_file_gr <- GRanges(
  bed_file_encode$chrom,
  IRanges(bed_file_encode$start, bed_file_encode$stop)
)
# Find the overlaps for both breakpoint1 and breakpoint2
overlaps1 <- findOverlaps(Ig_caller_df_cfWGS_filtered_gr1, bed_file_gr)
overlaps2 <- findOverlaps(Ig_caller_df_cfWGS_filtered_gr2, bed_file_gr)

# Get the indices of the overlapping entries for both breakpoints
overlap_indices1 <- queryHits(overlaps1)
overlap_indices2 <- queryHits(overlaps2)

# Combine the indices from both breakpoints, removing duplicates
all_overlap_indices <- unique(c(overlap_indices1, overlap_indices2))

# Use the combined indices to filter the data frame - to remove entries that overlap
Ig_caller_df_cfWGS_filtered_no_encode <- Ig_caller_df_cfWGS_filtered[-all_overlap_indices,]
Ig_caller_df_cfWGS_filtered_encode <- Ig_caller_df_cfWGS_filtered[all_overlap_indices,]
## Plot some characteristics of genes affected by more than one patient 

# Get number of patients 

# Group the data by IG_gene and Other_gene and count the unique Patient_ID occurrences
Ig_caller_df_cfWGS_filtered_patient <- Ig_caller_df_cfWGS_filtered_no_encode %>% dplyr::select(Patient, IG_gene, Other_gene, IGCaller_Score) %>% unique() %>% 
  group_by(IG_gene, Other_gene) %>%
  summarise(num_patients = n_distinct(Patient),
            avg_score = mean(IGCaller_Score, na.rm = TRUE),
            median_score = median(IGCaller_Score, na.rm = TRUE),
            sd_score = sd(IGCaller_Score, na.rm = TRUE)) %>%
  ungroup()

## Get only for BM cells 
#BM_cell_patients <- length(unique(samples_available_MYL2$Patient[grepl("BM_cells", samples_available_MYL2$Sample_type)]))


# Add columns 
#Ig_caller_df_cfWGS_filtered_patient <- left_join(Ig_caller_df_cfWGS_filtered_patient, Ig_caller_df_cfWGS_filtered %>% dplyr::select(IG_gene, Other_gene, break1_chromosome, break2_chromosome))

# Create some barplots showing the types of genes involved 

# Create a new column that combines IG_gene and Other_gene values
Ig_caller_df_cfWGS_filtered_patient$gene_pair <- paste(Ig_caller_df_cfWGS_filtered_patient$IG_gene, Ig_caller_df_cfWGS_filtered_patient$Other_gene, sep = "-")

# Order the data frame by num_patients in descending order
Ig_caller_df_cfWGS_filtered_patient <- Ig_caller_df_cfWGS_filtered_patient %>%
  arrange(desc(num_patients))





#### Create some plots to see the rearrangements captured 
# All patients
png(file = support_png(paste0("Frequency of repeating rearrangements across patients in cfWGS, all filtered calls", Sys.Date(), ".png")), width = 10, height = 5, units = "in", res = 500)
ggplot(Ig_caller_df_cfWGS_filtered_patient %>% filter(num_patients > 3), aes(x = reorder(gene_pair, num_patients), y = num_patients, fill = median_score)) +
  geom_bar(stat = "identity") +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_classic() +
  labs(x = "Rearrangement", y = "Number of Patients", title = "Frequency of reurring rearrangements across patients",
       subtitle = "Ig oncogenic fusions generated using Ig caller on cfWGS") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.margin = unit(c(0.1, 0.1, 0.1, 0.75), "in")) +
  geom_hline(yintercept = 10, linetype = "dashed", alpha = 0.5) +
  geom_text(aes(label = num_patients), vjust = -0.5, size = 3)
dev.off()

## Do a histogram
png(file = support_png(paste0("Histogram of fusions across patients in cfWGS", Sys.Date(), ".png")), width = 10, height = 5, units = "in", res = 500)
ggplot(Ig_caller_df_cfWGS_filtered_patient,
       aes(x = num_patients, y = after_stat(count))) +
  geom_histogram(binwidth = 1, color = "black", fill = "lightblue") +
  theme_classic() +
  labs(x = "Number of patients a fusion occurs in", y = "Number of fusions", 
       title = "Frequency of Ig fusions across patients",
       subtitle = "Ig oncogenic fusions generated using Ig caller on cfWGS") +
  scale_x_continuous(breaks = seq(0, max(Ig_caller_df_cfWGS_filtered_patient$num_patients), 1)) +
  theme(plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in")) + 
  geom_text(stat = "count", aes(label = after_stat(count)), vjust = -0.5, size = 3)
dev.off()


## Now create a new barplot with only fusions likely to be invovled in MM


## Create more aggressive filter for poor mapping region
# Apply more aggressive filter while allowing relevant myeloma genes to pass regardless of score
Ig_caller_df_cfWGS_filtered_aggressive <- Ig_caller_df_cfWGS_filtered_no_encode %>%
  filter(
    # Keep if there is a mappability issue and score is at least 100
    (Mappability_Issue != "none" & IGCaller_Score >= 100) |
      # Or if there is no mappability issue and score is at least 50
      (Mappability_Issue == "none" & IGCaller_Score >= 50) |
      # Or if it is a common MM translocation and the score is over 15
      (Common_MM_translocation == 1 & IGCaller_Score > 15) |
      # Keep all translocations involving relevant myeloma genes, regardless of score
      (Other_gene %in% relevant_myeloma_genes)
  ) %>%
  filter(Potential_MM_translocation == 1 | Other_gene %in% relevant_myeloma_genes)


#Group the data by IG_gene and Other_gene and count the unique Patient_ID occurrences
Ig_caller_df_cfWGS_filtered_patient_aggressive <- Ig_caller_df_cfWGS_filtered_aggressive %>%
  group_by(IG_gene, Other_gene) %>%
  summarise(num_patients = n_distinct(Patient),
            avg_score = mean(IGCaller_Score, na.rm = TRUE),
            median_score = median(IGCaller_Score, na.rm = TRUE),
            sd_score = sd(IGCaller_Score, na.rm = TRUE)) %>%
  ungroup()

# Create a new column that combines IG_gene and Other_gene values
Ig_caller_df_cfWGS_filtered_patient_aggressive$gene_pair <- paste(Ig_caller_df_cfWGS_filtered_patient_aggressive$IG_gene, Ig_caller_df_cfWGS_filtered_patient_aggressive$Other_gene, sep = "-")

# Order the data frame by num_patients in descending order
Ig_caller_df_cfWGS_filtered_patient_aggressive <- Ig_caller_df_cfWGS_filtered_patient_aggressive %>%
  arrange(desc(num_patients))

## Need to get the Common MM and potential MM columns
Ig_caller_df_cfWGS_filtered_patient <- left_join(Ig_caller_df_cfWGS_filtered_patient, Ig_caller_df_cfWGS_filtered_no_encode %>% dplyr::select(IG_gene, Other_gene, Common_MM_translocation, Potential_MM_translocation, Sorted_translocation))
Ig_caller_df_cfWGS_filtered_patient <- unique(Ig_caller_df_cfWGS_filtered_patient)

Ig_caller_df_cfWGS_filtered_patient_aggressive <- left_join(Ig_caller_df_cfWGS_filtered_patient_aggressive, Ig_caller_df_cfWGS_filtered_no_encode %>% dplyr::select(IG_gene, Other_gene, Common_MM_translocation, Potential_MM_translocation, Sorted_translocation))
Ig_caller_df_cfWGS_filtered_patient_aggressive <- unique(Ig_caller_df_cfWGS_filtered_patient_aggressive)

## Plot again but filter that Potential == 1

# All patients - top 50 variants
png(file = support_png(paste0("Frequency of repeating rearrangements across patients, only MM chromosomes in cfWGS - top 50 ", Sys.Date(), ".png")), width = 10, height = 5, units = "in", res = 500)

top_50_variants <- Ig_caller_df_cfWGS_filtered_patient %>%
  filter(num_patients > 2) %>%
  filter(Potential_MM_translocation == 1) %>%
  arrange(desc(num_patients)) %>%
  head(50)

ggplot(top_50_variants, aes(x = reorder(gene_pair, num_patients), y = num_patients, fill = median_score)) +
  geom_bar(stat = "identity") +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_classic() +
  labs(x = "Rearrangement", y = "Number of Patients", title = "Top 50 Frequency of recurring rearrangements across patients, only MM chromosomes",
       subtitle = "Ig oncogenic fusions generated using Ig caller on 30-40X WGS") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.margin = unit(c(0.1, 0.1, 0.1, 0.75), "in")) +
  geom_hline(yintercept = 10, linetype = "dashed", alpha = 0.5) +
  geom_text(aes(label = num_patients), vjust = -0.5, size = 3)

dev.off()


# Common MM cytobands - top 50 variants
png(file = support_png(paste0("Frequency of repeating rearrangements across patients, only MM cytobands in cfWGS - top 50 ", Sys.Date(), ".png")), width = 10, height = 5, units = "in", res = 500)

top_50_common_variants <- Ig_caller_df_cfWGS_filtered_patient %>%
  filter(num_patients > 0) %>%
  filter(Common_MM_translocation == 1) %>%
  arrange(desc(num_patients)) %>%
  head(50)

ggplot(top_50_common_variants, aes(x = reorder(gene_pair, num_patients), y = num_patients, fill = median_score)) +
  geom_bar(stat = "identity") +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_classic() +
  labs(x = "Rearrangement", y = "Number of Patients", title = "Top 50 Frequency of recurring rearrangements across patients, only MM cytobands",
       subtitle = "Ig oncogenic fusions generated using Ig caller on 30-40X WGS") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.margin = unit(c(0.1, 0.1, 0.1, 0.75), "in")) +
  geom_text(aes(label = num_patients), vjust = -0.5, size = 3)

dev.off()

## More agressive filtering 

# Filter out rows where Other_gene starts with "LOC" or "LINC" since likely artifact unless very high score
# Uncharacterised loci (LOC*) and long intergenic non-coding RNAs (LINC*) are
# disproportionately detected by Ig_caller in low-complexity genomic regions.
# Applying a strict score threshold (> 200) retains only those with strong
# split-read/discordant-pair evidence, reducing false-positive burden before
# the final patient-frequency filter.
Ig_caller_df_cfWGS_filtered_aggressive <- Ig_caller_df_cfWGS_filtered_aggressive %>%
  filter(!(grepl("^LOC|^LINC", Other_gene) & IGCaller_Score <= 200))

# More aggressive filtering - top 50 variants
png(file = support_png(paste0("Frequency of repeating rearrangements across patients, only MM chromosomes in cfWGS, more aggressive filtering - top 50 ", Sys.Date(), ".png")), width = 10, height = 5, units = "in", res = 500)

top_50_aggressive_variants <- Ig_caller_df_cfWGS_filtered_patient_aggressive %>%
  filter(num_patients >= 1) %>%
  filter(Common_MM_translocation == 1) %>%
  arrange(desc(num_patients)) %>%
  head(50)

ggplot(top_50_aggressive_variants, aes(x = reorder(gene_pair, num_patients), y = num_patients, fill = median_score)) +
  geom_bar(stat = "identity") +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_classic() +
  labs(x = "Rearrangement", y = "Number of Patients", title = "Top 50 Frequency of recurring rearrangements across patients, only MM chromosomes, more aggressive filtering",
       subtitle = "Ig oncogenic fusions generated using Ig caller on 30-40X WGS") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.margin = unit(c(0.1, 0.1, 0.1, 0.75), "in")) +
  geom_hline(yintercept = 10, linetype = "dashed", alpha = 0.5) +
  geom_text(aes(label = num_patients), vjust = -0.5, size = 3)

dev.off()

## Keep the aggressive filter because seems to get rid of most of artifacts, 
## remove variants found in more than 5 patients, about 10% 

# List of key myeloma genes to retain
key_myeloma_genes <- c(
  "CCND1",  # t(11;14) - Cyclin D1 activation
  "FGFR3",  # t(4;14) - FGFR3 activation
  "NSD2",   # t(4;14) - Also called MMSET/WHSC1, chromatin modifier
  "MAF",    # t(14;16) - MAF oncogene activation
  "MAFB",   # t(14;20) - MAFB oncogene activation
  "MYC",    # t(8;14) - MYC overexpression (rare but aggressive)
  "CCND3",  # t(6;14) - Cyclin D3 activation
  "IRF4"    # t(1;14) - IRF4 activation, plasma cell differentiation
)

# Group by IG_gene and Other_gene and count the number of distinct patients with each combination
# Calls found in > 2 patients (and not involving a key myeloma gene with
# Common_MM_translocation == 1) are flagged as probable pan-cohort artefacts
# (e.g. recurrent mapping artefacts at immunoglobulin gene cluster boundaries).
# Key myeloma genes are always retained regardless of patient count because
# their high prevalence in MM is biologically expected, not technical noise.
Ig_caller_df_cfWGS_filtered_aggressive <- Ig_caller_df_cfWGS_filtered_aggressive %>%
  group_by(IG_gene, Other_gene) %>%
  mutate(patient_count = n_distinct(Patient)) %>%  # Count distinct patients per gene combination
  ungroup() %>%
  # Filter to keep combinations found in 2 or fewer patients,
  # or keep if Other_gene is a key myeloma gene and it is a common MM translocation
  filter(patient_count <= 2 | 
           (Other_gene %in% key_myeloma_genes & Common_MM_translocation == 1))

write_support_rds(Ig_caller_df_cfWGS_filtered_aggressive, "Oct_2024_Ig_caller_df_cfWGS_filtered_aggressive.rds")

# Stricter filtering 
# while retaining other cases for manual review
Ig_caller_df_cfWGS_filtered_aggressive2 <- Ig_caller_df_cfWGS_filtered_aggressive %>%
  filter(
    # Exclude rows where Mappability_Issue is not "none" and IGCaller_Score <= 100
    !(Mappability_Issue != "none" & IGCaller_Score <= 100)
  ) %>%
  filter(
    # Exclude rows where IGCaller_Score is <= 20, even if Other_gene is NSD2 or MAF
    !(IGCaller_Score <= 20 & Other_gene %in% c("NSD2", "MAF"))
  ) %>%
  filter(
    # Keep rows meeting the following criteria:
    (Mappability_Issue == "none" & IGCaller_Score >= 50) |   # Moderate-confidence calls without mappability issues
      (Common_MM_translocation == 1 & IGCaller_Score >= 40) |  # Low-threshold for common MM translocations
      (Other_gene %in% relevant_myeloma_genes)                # Retain relevant MM genes regardless of score
  )


## Redo patient count 
Ig_caller_df_cfWGS_filtered_aggressive2 <- Ig_caller_df_cfWGS_filtered_aggressive2 %>%
  group_by(IG_gene, Other_gene) %>%
  mutate(patient_count = n_distinct(Patient)) %>%  # Count distinct patients per gene combination
  ungroup()

write_support_rds(Ig_caller_df_cfWGS_filtered_aggressive, "Jan_2025_Ig_caller_df_cfWGS_filtered_aggressive.rds")
write_support_rds(Ig_caller_df_cfWGS_filtered_aggressive2, "Jan_2025_Ig_caller_df_cfWGS_filtered_extra_aggressive.rds")


#### Now plot

# Create a matrix-like structure with unique combinations of Bam_File, Patient, Timepoint
# Filter for max score to have one row per patient
translocation_matrix <- Ig_caller_df_cfWGS_filtered_aggressive2 %>%
  filter(Other_gene %in% key_myeloma_genes) %>%  # Filter only rows with key translocations
  filter(Common_MM_translocation == 1) %>% 
  group_by(Bam_File) %>%  # Group by Bam_File to identify duplicates
  slice_max(order_by = IGCaller_Score, n = 1, with_ties = FALSE) %>%  # Keep only the row with the highest score
  ungroup() %>%
  dplyr::select(Bam_File, Patient, Timepoint, Sample_type, Sample_ID, timepoint_info, IG_gene, Other_gene) %>%  # Select relevant columns
  distinct() %>%  # Remove duplicates
  # Collapse specific IGH subtypes into general "IGH"
  mutate(IG_gene = ifelse(grepl("^IGH", IG_gene), "IGH", IG_gene)) %>%
  mutate(Translocation = paste(IG_gene, Other_gene, sep = "-")) %>%  # Create a new translocation column
  pivot_wider(
    names_from = Translocation,  # Columns for each translocation
    values_from = Translocation,  # Use the same column to create 1/0
    values_fn = list(Translocation = ~1),  # Set to 1 where translocation exists
    values_fill = 0  # Fill with 0 where translocation doesn't exist
  )


# Correct the summarization of IGH translocations
summarised_translocation_matrix <- translocation_matrix %>%
  # Summarize the IGH translocations by checking if any IGH-related columns have a value of 1
  mutate(IGH_translocation = ifelse(rowSums(across(contains("IGH-"))) > 0, 1, 0)) %>%
  # Drop the individual IGH-* columns
  dplyr::select(-starts_with("IGH-"))  # Remove individual IGH-* columns after collapsing


### Make a seperate one for cytoband 
# Create a matrix-like structure with unique combinations of Bam_File, Patient, Timepoint, etc.
translocation_matrix_cytoband <- Ig_caller_df_cfWGS_filtered_aggressive2 %>%
  filter(Common_MM_translocation == 1) %>%  # Filter rows with common MM translocations
  group_by(Bam_File) %>%  # Group by Bam_File to handle duplicates
  slice_max(order_by = IGCaller_Score, n = 1, with_ties = FALSE) %>%  # Keep only the row with the highest score
  ungroup() %>%
  dplyr::select(Bam_File, Patient, Timepoint, Sample_type, Sample_ID, timepoint_info, Sorted_translocation) %>%  # Select relevant columns
  distinct() %>%  # Remove duplicates
  # Collapse specific IGH subtypes into general "IGH" in the Sorted_translocation column
  mutate(Sorted_translocation = ifelse(grepl("^IGH", Sorted_translocation), sub("_.*", "", Sorted_translocation), Sorted_translocation)) %>%
  pivot_wider(
    names_from = Sorted_translocation,  # Create columns for each translocation type
    values_from = Sorted_translocation,  # Use the same column to create 1/0
    values_fn = list(Sorted_translocation = ~1),  # Set to 1 where translocation exists
    values_fill = 0  # Fill with 0 where translocation doesn't exist
  )


### Now export the screenshotter dataframes for these 
# 1) pivot both breakpoints into one table
screenshotter_df <- Ig_caller_df_cfWGS_filtered_aggressive2 %>%
  filter(Common_MM_translocation == 1) %>% 
  select(
    Bam        = Bam_File,
    Chromosome = break1_chromosome,
    Start      = break1_position_start,
    End        = break1_position_end,
    Name       = Translocation
  ) %>%
  distinct() %>%
  mutate(
    # pull 50 bp upstream, but not below 1:
    Start = pmax(1, Start - 50),
    # push 50 bp downstream:
    End   = End   + 50
  )

# 2) load the “canonical” list of BAMs (no .bam suffix)
current_bams <- read_csv("IG_Mini_Bams.csv")$Name %>%
  str_remove("\\.bam$")

# Detect missing BAM names. The historical code maps every missing name to its
# nearest Levenshtein match without a maximum-distance cutoff; inspect the
# printed `result` before using the generated BED files for manual review.
screenshot_bams <- str_remove(screenshotter_df$Bam, "\\.bam$")
missing_bams    <- setdiff(screenshot_bams, current_bams)

library(stringdist)

# For each missing BAM, find the closest match in current_bams based on Levenshtein distance
closest_matches <- sapply(missing_bams, function(miss) {
  distances <- stringdist(miss, current_bams, method = "lv")
  current_bams[which.min(distances)]
})

# Combine results into a data frame and print
result <- data.frame(
  Missing_BAM = missing_bams,
  Closest_Match = closest_matches,
  stringsAsFactors = FALSE
)
print(result)

# Historical manually inspected names. This `keep` vector is not referenced by
# the mapping statements below and therefore does not restrict replacements.
keep <- c(
  "TFRIM4_0060_Bm_P_WG_FZ-09.filter.deduped.recalibrated",
  "TFRIM4_0178_Bm_P_WG_FZ-07.filter.deduped.recalibrated",
  "TFRIM4_0184_Bm_P_WG_VA-10-01-O-DNA.filter.deduped.recalibrated",
  "TFRIM4_0187_Bm_P_WG_VA-13-01-O-DNA.filter.deduped.recalibrated"
)

# 3. apply any name fixes, then split out groups
screenshotter_df <- screenshotter_df %>%
  mutate(Bam = str_remove(Bam, "\\.bam$")) %>%
  left_join(result, by = c("Bam" = "Missing_BAM")) %>%
  mutate(Bam = coalesce(Closest_Match, Bam)) %>%
  select(-Closest_Match)

# 4. write BEDs
outdir_bed <- "IGV_screenshotter/Bed_files_translocations_cytoband"
if (!dir.exists(outdir_bed)) dir.create(outdir_bed, recursive = TRUE)

write_bed <- function(df, bam_name) {
  bed <- df %>%
    mutate(
      Chromosome = if_else(str_starts(Chromosome,"chr"), Chromosome, paste0("chr",Chromosome)),
      Start      = Start,
      End        = End
    ) %>%
    select(Chromosome, Start, End, Name)
  # write into the outdir:
  write_tsv(bed,
            file.path(outdir_bed, paste0(bam_name, ".bed")),
            col_names = FALSE)
}
  

screenshotter_df %>%
  group_by(Bam) %>%
  group_walk(~ write_bed(.x, .y$Bam))


### Now do for the breakpoint 2
# 1) pivot both breakpoints into one table
screenshotter_df <- Ig_caller_df_cfWGS_filtered_aggressive2 %>%
  filter(Common_MM_translocation == 1) %>% 
  select(
    Bam        = Bam_File,
    Chromosome = break2_chromosome,
    Start      = break2_position_start,
    End        = break2_position_end,
    Name       = Translocation
  ) %>%
  distinct() %>%
  mutate(
    # pull 50 bp upstream, but not below 1:
    Start = pmax(1, Start - 50),
    # push 50 bp downstream:
    End   = End   + 50
  )

# 2) load the “canonical” list of BAMs (no .bam suffix)
current_bams <- read_csv("IG_Mini_Bams.csv")$Name %>%
  str_remove("\\.bam$")

# Detect missing BAM names. As above, mapping uses the nearest inventory string
# without a maximum-distance cutoff and prints the proposed replacements.
screenshot_bams <- str_remove(screenshotter_df$Bam, "\\.bam$")
missing_bams    <- setdiff(screenshot_bams, current_bams)

# For each missing BAM, find the closest match in current_bams based on Levenshtein distance
closest_matches <- sapply(missing_bams, function(miss) {
  distances <- stringdist(miss, current_bams, method = "lv")
  current_bams[which.min(distances)]
})

# Combine results into a data frame and print
result <- data.frame(
  Missing_BAM = missing_bams,
  Closest_Match = closest_matches,
  stringsAsFactors = FALSE
)
print(result)

# Historical manually inspected names; this vector is not used downstream.
keep <- c(
  "TFRIM4_0060_Bm_P_WG_FZ-09.filter.deduped.recalibrated",
  "TFRIM4_0178_Bm_P_WG_FZ-07.filter.deduped.recalibrated",
  "TFRIM4_0184_Bm_P_WG_VA-10-01-O-DNA.filter.deduped.recalibrated",
  "TFRIM4_0187_Bm_P_WG_VA-13-01-O-DNA.filter.deduped.recalibrated"
)

# 3. apply any name fixes, then split out groups
screenshotter_df <- screenshotter_df %>%
  mutate(Bam = str_remove(Bam, "\\.bam$")) %>%
  left_join(result, by = c("Bam" = "Missing_BAM")) %>%
  mutate(Bam = coalesce(Closest_Match, Bam)) %>%
  select(-Closest_Match)

# 4. write BEDs
outdir_bed <- "IGV_screenshotter/Bed_files_translocations_cytoband_breakpoint_2"
if (!dir.exists(outdir_bed)) dir.create(outdir_bed, recursive = TRUE)

write_bed <- function(df, bam_name) {
  bed <- df %>%
    mutate(
      Chromosome = if_else(str_starts(Chromosome,"chr"), Chromosome, paste0("chr",Chromosome)),
      Start      = Start,
      End        = End
    ) %>%
    select(Chromosome, Start, End, Name)
  # write into the outdir:
  write_tsv(bed,
            file.path(outdir_bed, paste0(bam_name, ".bed")),
            col_names = FALSE)
}


screenshotter_df %>%
  group_by(Bam) %>%
  group_walk(~ write_bed(.x, .y$Bam))


add_col_if_missing <- function(df, colname, default = NA_integer_) {
  if (!colname %in% colnames(df)) {
    df[[colname]] <- default
  }
  df
}



gene_translocation_cols <- c("IGH-MAF", "IGH-CCND1", "IGH-MYC", "IGH-FGFR3")
for (col in gene_translocation_cols) {
  translocation_matrix <- add_col_if_missing(translocation_matrix, col, default = 0L)
}

translocation_feature_cols <- setdiff(
  names(translocation_matrix),
  c("Bam_File", "Patient", "Timepoint", "Sample_type", "Sample_ID", "timepoint_info")
)
translocation_matrix <- translocation_matrix %>%
  mutate(across(all_of(translocation_feature_cols), ~ replace_na(as.integer(.x), 0L)))

#  Prepare translocation data
translocation_data <- translocation_matrix %>%
  select(Bam_File, IGH_MAF = `IGH-MAF`, IGH_CCND1 = `IGH-CCND1`, IGH_MYC = `IGH-MYC`, IGH_FGFR3 = `IGH-FGFR3`) %>%
  mutate(Sample = gsub(".bam$", "", Bam_File))  # Remove '.bam' extension if present

cyto_cols <- c(
  "chr11q13.2_chr14q32.33",
  "chr11q13.3_chr14q32.33",
  "chr14q32.33_chr4p16.3",
  "chr14q32.33_chr16q23.2",
  "chr14q32.33_chr8q24.21"
)
for (col in cyto_cols) {
  translocation_matrix_cytoband <- add_col_if_missing(translocation_matrix_cytoband, col, default = 0L)
}

translocation_data_cytoband <- translocation_matrix_cytoband %>%
  # A t(11;14) call may be assigned to either adjacent 11q13 cytoband.
  # Combine the two binary indicators with OR rather than coalesce(): absent
  # calls are encoded as 0, so coalesce(0, 1) would incorrectly return 0.
  mutate(
    IGH_CCND1 = pmax(
      coalesce(.data[["chr11q13.2_chr14q32.33"]], 0L),
      coalesce(.data[["chr11q13.3_chr14q32.33"]], 0L)
    )
  ) %>%
  # now pick off and rename all four
  transmute(
    Bam_File = Bam_File,
    Sample      = gsub(".bam$", "", Bam_File),        # drop “.bam”
    IGH_CCND1,                                     
    IGH_FGFR3 = `chr14q32.33_chr4p16.3`,
    IGH_MAF   = `chr14q32.33_chr16q23.2`,
    IGH_MYC   = `chr14q32.33_chr8q24.21`
  )

## Export automated translocation feature tables
# These are useful intermediates, but the final cytoband matrix below is rebuilt
# after manual IGV confirmation using the reviewed xlsm file.
# Define export directories. Final IGV-confirmed outputs remain in
# Jan2025_exported_data because downstream scripts read them there; automated
# pre-IGV helper matrices are support-only.
export_dir <- "Jan2025_exported_data"
pre_igv_dir <- file.path(support_table_dir, "pre_igv_feature_matrices")
dir.create(export_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(pre_igv_dir, recursive = TRUE, showWarnings = FALSE)

# Exporting dataframes as RDS files
saveRDS(translocation_data, file = file.path(pre_igv_dir, "translocation_data.rds"))
saveRDS(translocation_data_cytoband, file = file.path(pre_igv_dir, "translocation_data_cytoband.rds"))

# Exporting dataframes as text files
write.table(translocation_data, file = file.path(pre_igv_dir, "translocation_data.txt"), sep = "\t", row.names = FALSE, quote = FALSE)
write.table(translocation_data_cytoband, file = file.path(pre_igv_dir, "translocation_data_cytoband.txt"), sep = "\t", row.names = FALSE, quote = FALSE)


## Export candidate calls for manual IGV checking
# The resulting text file is the input to the IGV review workbook. The final
# cytoband translocation matrix used in the manuscript is rebuilt only from calls
# marked Looks_real == 1 in the reviewed workbook.
filtered_df <- Ig_caller_df_cfWGS_filtered_aggressive2 %>%
  dplyr::filter(
    timepoint_info %in% c("Baseline", "Diagnosis"),
    Patient %in% cohort_df$Patient,
    Common_MM_translocation == 1
  )

spring2026_revision_metadata_for_igv <- load_spring2026_revision_metadata(required = FALSE)
if (!is.null(spring2026_revision_metadata_for_igv)) {
  spring2026_revision_patients_for_igv <- spring2026_revision_metadata_for_igv %>%
    filter(!is.na(.data$Patient), nzchar(.data$Patient)) %>%
    distinct(.data$Patient) %>%
    pull(.data$Patient)

  # Keep a complete review queue as well as the smaller baseline table below.
  # Nothing in this file is promoted until the manual IGV result is recorded.
  spring2026_all_igv_candidates <- Ig_caller_df_cfWGS_filtered_aggressive2 %>%
    filter(
      .data$Patient %in% spring2026_revision_patients_for_igv,
      .data$Sample_type %in% c("BM_cells", "Blood_plasma_cfDNA")
    ) %>%
    distinct(
      .data$Patient,
      .data$Sample_ID,
      .data$Bam_File,
      .data$breakpoint1,
      .data$breakpoint2,
      .keep_all = TRUE
    ) %>%
    mutate(
      review_priority = case_when(
        .data$timepoint_info %in% c("Baseline", "Diagnosis") &
          .data$Common_MM_translocation == 1 ~ "1_baseline_common_MM",
        .data$timepoint_info %in% c("Baseline", "Diagnosis") &
          .data$Other_gene %in% key_myeloma_genes ~ "2_baseline_driver_gene",
        .data$timepoint_info %in% c("Baseline", "Diagnosis") ~ "3_baseline_other",
        .data$Common_MM_translocation == 1 ~ "4_longitudinal_common_MM",
        .data$Other_gene %in% key_myeloma_genes ~ "5_longitudinal_driver_gene",
        TRUE ~ "6_longitudinal_other"
      ),
      manual_review_status = "not_reviewed",
      Looks_real = NA_real_,
      IGV_notes = NA_character_,
      final_matrix_status = "not_promoted_until_Looks_real_1_in_reviewed_xlsm"
    ) %>%
    arrange(
      .data$review_priority,
      .data$Patient,
      .data$Sample_ID,
      desc(.data$IGCaller_Score)
    )

  readr::write_csv(
    spring2026_all_igv_candidates,
    support_path("spring2026_IgCaller_all_passing_BM_cfDNA_calls_for_IGV_review.csv")
  )

  # This is the smaller set that can enter the baseline translocation matrix
  # after review.
  spring2026_igv_candidates <- filtered_df %>%
    # Match patients rather than sample IDs because the same library sometimes
    # has an older MyP/MyR name and a newer IMG name. Matching sample IDs would
    # miss those calls.
    filter(.data$Patient %in% spring2026_revision_patients_for_igv) %>%
    distinct(
      .data$Patient,
      .data$Sample_ID,
      .data$Bam_File,
      .data$breakpoint1,
      .data$breakpoint2,
      .keep_all = TRUE
    ) %>%
    mutate(
      manual_review_status = "candidate_requires_IGV_review_before_feature_matrix",
      final_matrix_status = "not_promoted_until_Looks_real_1_in_reviewed_xlsm"
    ) %>%
    arrange(.data$Patient, .data$Sample_ID, desc(.data$IGCaller_Score))
  readr::write_csv(
    spring2026_igv_candidates,
    support_path("spring2026_IgCaller_common_MM_translocation_candidates_for_IGV_review.csv")
  )
}

write.table(
  filtered_df,
  file = file.path(export_dir, "Ig_caller_df_cfWGS_filtered_aggressive2_iGV_check.txt"),
  sep = "\t",
  row.names = FALSE,
  quote = FALSE
)

### Read and combine the IGV-reviewed call tables
# After automated filtering, each candidate common MM translocation at a
# diagnosis/baseline timepoint was manually reviewed in IGV using the mini-BAM
# files generated by the IGV_screenshotter workflow. Historical calls remain in
# the original xlsm without modification. Newly adjudicated revision calls live
# in a separate tracked TSV and are matched back to the current parsed IgCaller
# table by patient, BAM, and both exact breakpoints. This prevents the revision
# review from changing or overriding an original call.
legacy_igv_review_path <- file.path(
  export_dir,
  "Ig_caller_df_cfWGS_filtered_aggressive2_iGV_check.xlsm"
)
revision_igv_review_path <- first_existing(
  c(
    file.path(
      "Scripts_2025", "Final_Scripts", "data", "curation",
      "igcaller_revision_2026_igv_review.tsv"
    ),
    file.path("data", "curation", "igcaller_revision_2026_igv_review.tsv")
  ),
  "revision IgCaller IGV review table"
)

legacy_igv_review <- readxl::read_excel(legacy_igv_review_path)
revision_igv_review <- readr::read_tsv(
  revision_igv_review_path,
  show_col_types = FALSE,
  progress = FALSE
)

review_key <- c("Patient", "Bam_File", "breakpoint1", "breakpoint2")
required_revision_review_columns <- c(
  "call_id", review_key, "Looks_real", "review_status", "IGV_notes"
)
missing_revision_review_columns <- setdiff(
  required_revision_review_columns,
  names(revision_igv_review)
)
if (length(missing_revision_review_columns) > 0L) {
  stop(
    "Revision IgCaller IGV review table is missing required columns: ",
    paste(missing_revision_review_columns, collapse = ", "),
    call. = FALSE
  )
}
if (anyDuplicated(revision_igv_review$call_id)) {
  stop("Revision IgCaller IGV review table contains duplicate call_id values.", call. = FALSE)
}
if (anyDuplicated(revision_igv_review[review_key])) {
  stop("Revision IgCaller IGV review table contains duplicate exact call keys.", call. = FALSE)
}
allowed_review_scores <- c(0, 0.25, 0.5, 0.75, 1)
if (
  any(is.na(revision_igv_review$Looks_real)) ||
    any(!revision_igv_review$Looks_real %in% allowed_review_scores)
) {
  stop(
    "Revision Looks_real values must be one of: ",
    paste(allowed_review_scores, collapse = ", "),
    call. = FALSE
  )
}
if (any(revision_igv_review$review_status != "adjudicated")) {
  stop("All rows in the revision review table must have review_status='adjudicated'.", call. = FALSE)
}

legacy_revision_overlap <- legacy_igv_review %>%
  semi_join(revision_igv_review, by = review_key)
if (nrow(legacy_revision_overlap) > 0L) {
  stop(
    "Revision review rows overlap historical reviewed calls. The historical ",
    "workbook must remain authoritative for original calls.",
    call. = FALSE
  )
}

revision_candidate_matches <- Ig_caller_df_cfWGS_filtered_aggressive2 %>%
  semi_join(revision_igv_review, by = review_key)
if (nrow(revision_candidate_matches) != nrow(revision_igv_review)) {
  unmatched_revision_calls <- revision_igv_review %>%
    anti_join(Ig_caller_df_cfWGS_filtered_aggressive2, by = review_key) %>%
    pull(.data$call_id)
  stop(
    "Expected one current IgCaller candidate for every revision review row. ",
    "Matched ", nrow(revision_candidate_matches), " of ",
    nrow(revision_igv_review), ". Unmatched call_id values: ",
    paste(unmatched_revision_calls, collapse = ", "),
    call. = FALSE
  )
}

revision_reviewed_calls <- revision_candidate_matches %>%
  inner_join(
    revision_igv_review %>%
      select(
        all_of(review_key),
        call_id,
        reviewed_Looks_real = Looks_real,
        review_confidence,
        review_status,
        reviewed_IGV_notes = IGV_notes
      ),
    by = review_key
  ) %>%
  mutate(
    Looks_real = .data$reviewed_Looks_real,
    Notes = .data$reviewed_IGV_notes,
    review_source = "revision_2026_tsv"
  )

review_matrix_columns <- c(
  "Bam_File", "Patient", "Timepoint", "Sample_type", "Sample_ID",
  "timepoint_info", "Sorted_translocation", "IGCaller_Score",
  "Common_MM_translocation", "Looks_real", "Notes"
)
missing_legacy_matrix_columns <- setdiff(
  review_matrix_columns,
  names(legacy_igv_review)
)
missing_revision_matrix_columns <- setdiff(
  review_matrix_columns,
  names(revision_reviewed_calls)
)
if (length(missing_legacy_matrix_columns) > 0L) {
  stop(
    "Historical IGV workbook is missing matrix columns: ",
    paste(missing_legacy_matrix_columns, collapse = ", "),
    call. = FALSE
  )
}
if (length(missing_revision_matrix_columns) > 0L) {
  stop(
    "Matched revision calls are missing matrix columns: ",
    paste(missing_revision_matrix_columns, collapse = ", "),
    call. = FALSE
  )
}

legacy_reviewed_calls <- legacy_igv_review %>%
  select(all_of(review_matrix_columns)) %>%
  mutate(review_source = "historical_xlsm")
revision_reviewed_calls_for_matrix <- revision_reviewed_calls %>%
  select(all_of(review_matrix_columns)) %>%
  mutate(review_source = "revision_2026_tsv")

iGV_reviewed_all <- bind_rows(
  legacy_reviewed_calls,
  revision_reviewed_calls_for_matrix
)
iGV_verified <- iGV_reviewed_all %>%
  filter(.data$Looks_real == 1)

revision_review_audit <- revision_reviewed_calls %>%
  transmute(
    .data$call_id,
    .data$Patient,
    .data$Sample_ID,
    .data$Bam_File,
    .data$breakpoint1,
    .data$breakpoint2,
    .data$Sorted_translocation,
    .data$IGCaller_Score,
    .data$Looks_real,
    .data$review_confidence,
    .data$review_status,
    IGV_notes = .data$Notes,
    final_matrix_status = if_else(
      .data$Looks_real == 1,
      "promoted_to_strict_matrix",
      "not_promoted_fractional_review_score"
    )
  ) %>%
  arrange(.data$Patient, .data$Sample_ID, desc(.data$IGCaller_Score))
readr::write_csv(
  revision_review_audit,
  support_path("revision_2026_IgCaller_IGV_review_application_audit.csv")
)
message(
  "Historical IGV calls retained unchanged: ", nrow(legacy_igv_review),
  "; revision calls appended: ", nrow(revision_reviewed_calls),
  "; revision strict calls promoted: ",
  sum(revision_reviewed_calls$Looks_real == 1)
)

## Filter to what checked 
translocation_matrix_cytoband <- iGV_verified %>%
  filter(Common_MM_translocation == 1) %>%  # Filter rows with common MM translocations
  group_by(Bam_File) %>%  # Group by Bam_File to handle duplicates
  slice_max(order_by = IGCaller_Score, n = 1, with_ties = FALSE) %>%  # Keep only the row with the highest score
  ungroup() %>%
  dplyr::select(Bam_File, Patient, Timepoint, Sample_type, Sample_ID, timepoint_info, Sorted_translocation) %>%  # Select relevant columns
  distinct() %>%  # Remove duplicates
  # Collapse specific IGH subtypes into general "IGH" in the Sorted_translocation column
  mutate(Sorted_translocation = ifelse(grepl("^IGH", Sorted_translocation), sub("_.*", "", Sorted_translocation), Sorted_translocation)) %>%
  pivot_wider(
    names_from = Sorted_translocation,  # Create columns for each translocation type
    values_from = Sorted_translocation,  # Use the same column to create 1/0
    values_fn = list(Sorted_translocation = ~1),  # Set to 1 where translocation exists
    values_fill = 0  # Fill with 0 where translocation doesn't exist
  )


# Add all needed columns if missing
for (col in cyto_cols) {
  translocation_matrix_cytoband <- add_col_if_missing(translocation_matrix_cytoband, col, default = 0L)
}


translocation_data_cytoband <- translocation_matrix_cytoband %>%
  # Treat either adjacent 11q13 cytoband as evidence of t(11;14). Explicitly
  # replace missing values with 0 before applying the binary OR via pmax().
  mutate(
    IGH_CCND1 = pmax(
      coalesce(.data[["chr11q13.2_chr14q32.33"]], 0L),
      coalesce(.data[["chr11q13.3_chr14q32.33"]], 0L)
    )
  ) %>%
  # now pick off and rename all four
  transmute(
    Bam_File = Bam_File,
    Sample      = gsub(".bam$", "", Bam_File),        # drop “.bam”
    IGH_CCND1,                                     
    IGH_FGFR3 = `chr14q32.33_chr4p16.3`,
    IGH_MAF   = `chr14q32.33_chr16q23.2`,
    IGH_MYC   = `chr14q32.33_chr8q24.21`
  )


## Final export consumed by downstream feature integration
# This is the translocation feature object used in the manuscript because it
# incorporates the manual IGV `Looks_real == 1` confirmation step.
saveRDS(translocation_data_cytoband, file = file.path(export_dir, "translocation_data_cytoband_updated.rds"))

# Exporting dataframes as text files
write.table(translocation_data_cytoband, file = file.path(export_dir, "translocation_data_cytoband_updated.txt"), sep = "\t", row.names = FALSE, quote = FALSE)
