# ──────────────────────────────────────────────────────────────────────────────
# 1_7C_Process_fragmentomics_data_dilution_series_updated.R
#
# Purpose  ────────────────────────────────────────────────────────────────────
#   1. Load *dilution-series* nucleosome-accessibility distance files (cfWGS) 
#      and matching PON (healthy) files.
#   2. Harmonize sample IDs, join clinical keys, compute per-site:
#        • Mean.Coverage
#        • Midpoint.Coverage  (at Positions -30, -15, 0, +15, +30)
#        • Midpoint.normalized
#        • Amplitude   (max of the periodogram)
#   3. For each site, calculate:
#        • Z-scores vs. healthy (PON) for Coverage, Midpoint, Amplitude
#        • Fold-changes (tumour vs. healthy) for the three metrics
#        • Thresholds placed 10% beyond the platform-matched healthy-control
#          z-score extremes
#        • Binary “Threshold” flags per sample for each metric
#   4. Extract the “MM_DARs_chromatin_activation” site rows, re-attach  
#      clinical metadata (Bam, Patient, Date_of_sample_collection).
#   5. Load insert_size_summary.tsv and fragment_scores.tsv (dilution cohort), 
#      harmonize sample IDs, and merge with the MM_DARs data.
#   6. Read and normalize the configured metadata file a second time for legacy
#      compatibility (`meta_df` is not joined into the active output).
#   7. Write the final table and supporting audit/statistics files.
#
# Inputs:
#   • Fragmentomics_data/Dilution_series/Metadata_dilution_series.csv
#   • Historical dilution nucleosome, insert-size, and fragment-score TSVs
#     under Fragmentomics_data/Dilution_series/
#   • Historical healthy-control TSVs under Fragmentomics_data/Normals/
#   • Spring 2026 XPlus dilution and matched-control TSVs resolved by helpers.R
#   • Results_Fragmentomics/fragmentomics_platform_harmonization_reference_parameters.csv
#     generated by 1_7B
#
# Outputs:
#         Results_Fragmentomics/Dilution_series/key_fragmentomics_info_dilution_series.csv
#         Results_Fragmentomics/Dilution_series/key_fragmentomics_info_dilution_series.rds
#         Results_Fragmentomics/Dilution_series/fragmentomics_platform_reference_thresholds_dilution.csv
#         Results_Fragmentomics/Dilution_series/fragmentomics_threshold_direction_sensitivity_audit.csv
#         Results_Fragmentomics/Dilution_series/fragmentomics_platform_harmonization_dilution_audit.csv
#         Results_Fragmentomics/Dilution_series/Griffin/griffin_per_site_metrics_dilution.tsv
#         Results_Fragmentomics/Dilution_series/Griffin/griffin_per_site_stats_dilution.tsv
#         Results_Fragmentomics/Dilution_series/spring2026_unmatched_dilution_fragmentomics_samples.csv
#           (only when unmatched samples exist)
#
# How to run:
#   Rscript Scripts_2025/Final_Scripts/1_7C_Process_fragmentomics_data_dilution_series_updated.R
#
# Manuscript outputs created/updated:
#   - None directly. This upstream script processes dilution-series
#     fragmentomics features that are scored and plotted in 3_1_part2.
#
# Author:  Dory Abelman
# Updated: 2025-06-06
# ──────────────────────────────────────────────────────────────────────────────
# Pipeline status:
#   Active upstream dependency. This script does not directly create a named
#   final manuscript figure/table, but downstream scripts depend on its cleaned
#   outputs for figure, table, or model generation.
#
# Statistical and reproducibility notes:
#   The t-tests compare sample rows and are not used as replicate-aware LOD
#   estimates. BH-adjusted values are calculated in the in-memory `fdr.data`
#   object but are not joined to either exported table. Active Threshold.* calls
#   use the ratio-appropriate split at fold-change 1; the historical >= 0 / > 0
#   rule is retained only in a separate sensitivity audit.
#

### 0.  PACKAGES & HELPER FUNCTIONS  ############################################
suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
  library(stringr)
  library(tidyr)
  library(data.table)
  library(GeneCycle)   # for periodogram()
})

.helpers_path <- file.path("Scripts_2025", "Final_Scripts", "helpers.R")
if (!file.exists(.helpers_path)) {
  .helpers_path <- "helpers.R"
}
source(.helpers_path)
rm(.helpers_path)

# Compute a z-score of x versus the vector y
calculate.zscore <- function(x, y) {
  (x - mean(y, na.rm = TRUE)) / sd(y, na.rm = TRUE)
}

# Helper to parse Fold-Change + p-value from t.test (group2 vs group1)
get.foldchange.p <- function(i, group1.idx, group2.idx) {
  test <- t.test(i[group2.idx], i[group1.idx], na.rm = TRUE)
  fc   <- mean(i[group2.idx], na.rm = TRUE) / mean(i[group1.idx], na.rm = TRUE)
  return(c(fc = fc, p = test$p.value))
}

# clean_sample: standardises cfWGS sample identifiers to the common
# project format used across all scripts. Three transformations applied:
#  1. Strip Illumina pipeline suffix "_Blood_plasma_cfDNA", replace with "-P"
#  2. Replace underscores with hyphens for M4/IMG-cohort sample IDs
#     (SPORE IDs already use hyphens and are left unchanged)
#  3. Rename "IMG" prefix to "MyP" to match clinical database naming.
# This function is replicated from 1_7A/B to keep the dilution script
# self-contained and reproducible without importing helpers.
clean_sample <- function(x) {
  x %>%
    str_replace("_Blood_plasma_cfDNA$", "-P") %>%
    ifelse(!str_starts(x, "SPORE"),
           str_replace_all(., "_", "-"),
           .) %>%
    str_replace("IMG", "MyP")
}


### 1.  DEFINE PATHS  ###########################################################
# DILUTION SERIES vs. MAIN COHORT - KEY DIFFERENCES:
# Unlike 1_7A / 1_7B (which process clinical patient plasma samples across
# multiple timepoints), this script processes *in-vitro* dilution-series
# samples: MM patient plasma spiked into healthy donor plasma at known
# tumour-fraction steps.
# Purpose: establish analytical sensitivity for each fragmentomics feature
# (GRIFFIN z-scores, FS, Proportion.Short) as a function of tumour fraction.
# The metadata file uses the historical column name `LOD` for the prepared
# dilution percentage (input tumour-fraction level), rather than for an
# assay-derived limit of detection. No clinical response comparisons are run.
#
# Point these to the *dilution-series* folders:

# 1a) Nucleosome-accessibility input (cfWGS for dilution series)
nuc_input.dir <- file.path("Fragmentomics_data", "Dilution_series")

# 1b) Nucleosome-accessibility PON folder (healthy controls)
nuc_pon.dir   <- file.path("Fragmentomics_data", "Normals")

# 1c) Insert-size + FS input (dilution series)
ins_fs.dir    <- file.path("Fragmentomics_data", "Dilution_series")

# 1d) Combined clinical CSV (used for joining Sample → Bam, Patient, Date…)
clinical.csv  <- file.path("Fragmentomics_data", "Dilution_series", "Metadata_dilution_series.csv")

# 1e) If you have additional dilution series metadata file (e.g. dilution percentages), put it here:
meta.csv      <- clinical.csv

# 1f) Output folder for dilution series results
out.dir       <- file.path("Results_Fragmentomics", "Dilution_series")
if (!dir.exists(out.dir)) dir.create(out.dir, recursive = TRUE)


### 2.  LOAD CLINICAL TABLE   ##################################
combined_clinical <- read_dilution_metadata_with_spring2026(clinical.csv)
# The dilution metadata helper appends Spring 2026 PWGVAL/M4CHIP dilution rows
# to the historical dilution-series metadata while preserving the same columns
# used by the legacy fragmentomics processing below.


### 3.  READ & PROCESS NUCLEOSOME-ACCESSIBILITY (cfWGS + PON)  ##################

# 3a) List dilution files separately by sequencing platform. The historical
# dilution series was sequenced on NovaSeq 6000; VA-09/VA-12/VA-13 were newly
# generated on NovaSeq XPlus and must never inherit the historical reference.
historical_results_files <- list.files(
  path = nuc_input.dir,
  pattern = "nucleosome_accessibility_distances.tsv$",
  full.names = TRUE
)
xplus_results_files <- spring2026_revision_files(
  "Fragmentomics_Pipeeline_Suite_all_outputs",
  "^2026-06-25_cfWGS_MM_fragmentomics_Revisions_Spring2026_PWGVAL_Dilution_series_nucleosome_accessibility_distances[.]tsv$"
)

# 3b) List PON (healthy) files; we only need the first one if they’re identical format
pon.files <- rev(sort(
  list.files(path = nuc_pon.dir,
             pattern = "nucleosome_accessibility_distances.tsv$",
             full.names = TRUE)
))
xplus_pon_files <- spring2026_revision_files(
  "Fragmentomics_Pipeeline_Suite_all_outputs",
  "^2026-06-30_cfWGS_MM_fragmentomics_Revisions_Spring2026_CHARM_Xplus_HC_nucleosome_accessibility_distances[.]tsv$"
)
if (!length(pon.files) || !length(xplus_pon_files)) {
  stop("Both NovaSeq 6000 and NovaSeq XPlus dilution healthy-control references are required.", call. = FALSE)
}

read_nucleosome_batch <- function(paths, platform, role) {
  if (!length(paths)) return(tibble())
  bind_rows(lapply(paths, function(path) {
    read_tsv(path, show_col_types = FALSE) %>%
      mutate(
        fragmentomics_sequencing_platform = platform,
        fragmentomics_sample_role = role,
        fragmentomics_source_file = basename(path)
      )
  }))
}

# 3c) Read in all cfWGS dilution series data, bind rows
cfWGS.data <- bind_rows(
  read_nucleosome_batch(historical_results_files, "NovaSeq 6000", "dilution_series"),
  read_nucleosome_batch(xplus_results_files, "NovaSeq XPlus", "dilution_series")
)

# 3d) If any “TGL49” columns snuck in as columns, drop them (same as main script)
if (any(grepl("TGL49", colnames(cfWGS.data)))) {
  cfWGS.data <- cfWGS.data[, !grepl("TGL49", colnames(cfWGS.data))]
}

# 3e) Preserve the original 26-library NovaSeq 6000 scoring reference for the
# historical VA-02 series. Use the 19 shared XPlus controls for the three new
# XPlus series. The 19 matched historical subset is used only for the raw-input
# platform transform below, not for historical z-score calculation.
classify_fragmentomics_material <- function(sample) {
  case_when(
    str_detect(sample, "(^|[-_])Cf([-_]|$)|_Cf_|-Cf-") ~ "cfDNA",
    str_detect(sample, "(^|[-_])Pb([-_]|$)|_Pb_|-Pb-") ~ "PB_cellular_or_buffy",
    str_detect(sample, "(^|[-_])Ct([-_]|$)|_Ct_|-Ct-") ~ "cellular_or_tissue",
    TRUE ~ "unknown"
  )
}
historical_pon_data <- read_nucleosome_batch(
  pon.files[[1]], "NovaSeq 6000", "healthy_control"
) %>%
  mutate(fragmentomics_material = classify_fragmentomics_material(.data$Sample)) %>%
  filter_fragmentomics_original_historical_controls()
xplus_pon_data <- read_nucleosome_batch(
  xplus_pon_files[[1]], "NovaSeq XPlus", "healthy_control"
) %>%
  mutate(fragmentomics_material = classify_fragmentomics_material(.data$Sample)) %>%
  filter_fragmentomics_shared_healthy_controls()
pon.data <- bind_rows(historical_pon_data, xplus_pon_data)

# 3f) Harmonize Sample names in cfWGS.data exactly as before,
#     then left_join(tmp.clin) to grab Bam/Patient/Date/timepoint_info
cfWGS.data <- cfWGS.data %>%
  mutate(
    Sample = clean_sample(Sample),
    Sample = if_else(! str_starts(Sample, "SPORE"),
                     Sample,      # keep SPORE as-is
                     Sample),
    Sample = str_replace(Sample, "IMG", "MyP")
  ) %>%
  left_join(combined_clinical, by = c("Sample" = "Merge")) %>%
  mutate(Cohort = "cfWGS")

unmatched_dilution_samples <- cfWGS.data %>%
  filter(is.na(Bam)) %>%
  distinct(Sample) %>%
  arrange(Sample)
if (nrow(unmatched_dilution_samples) > 0) {
  write_csv(
    unmatched_dilution_samples,
    file.path(out.dir, "spring2026_unmatched_dilution_fragmentomics_samples.csv")
  )
}

# 3g) Mark PON samples as “HBC” (healthy bank controls)
pon.data <- pon.data %>%
  mutate(
    Sample = clean_sample(Sample),
    Cohort = "HBC"
  )

# 3h) Build sample lists
# NOTE: unlike 1_7A, there are no clinical subgroups. The dilution samples are
# compared with controls from their own sequencing platform.
# The relevant grouping variable for sensitivity analysis is the known
# tumour fraction (from Metadata_dilution_series.csv, "LOD" column).
all.tumour.samples <- unique(cfWGS.data$Sample)
all.pon.samples    <- setdiff(unique(pon.data$Sample), "TGL49_0267_Pb_U_PE_428") # remove duplicate longitudinal
all.samples        <- c(all.tumour.samples, all.pon.samples)

sample_reference_map <- bind_rows(
  cfWGS.data %>% distinct(Sample, fragmentomics_sequencing_platform, fragmentomics_sample_role),
  pon.data %>% distinct(Sample, fragmentomics_sequencing_platform, fragmentomics_sample_role)
) %>% distinct(Sample, .keep_all = TRUE)
sample_platform <- setNames(sample_reference_map$fragmentomics_sequencing_platform, sample_reference_map$Sample)
sample_role <- setNames(sample_reference_map$fragmentomics_sample_role, sample_reference_map$Sample)

# 3i) Grab all sites present in the cfWGS (dilution) data
all.sites <- unique(cfWGS.data$site_name)


### 4.  INITIALIZE STORAGE FOR METRICS, SCORES, STATS  #########################
metrics.per.site <- list()
scores.per.site  <- list()

### BUILD SAMPLE LISTS FOR GROUP COMPARISONS #########################################################
tumour.samples     <- all.tumour.samples
pon.samples        <- all.pon.samples

all.samples <- c(tumour.samples, pon.samples)
all.sites   <- unique(cfWGS.data$site_name)


### UTILITY FUNCTIONS ##############################################################################
calculate.zscore <- function(x, y) {
  y <- y[is.finite(y)]
  if (length(y) < 2L || !is.finite(sd(y)) || sd(y) == 0) return(NA_real_)
  (x - mean(y)) / sd(y)
}

calculate_platform_zscores <- function(values, platforms, roles) {
  vapply(seq_along(values), function(i) {
    reference <- values[roles == "healthy_control" & platforms == platforms[[i]]]
    calculate.zscore(values[[i]], reference)
  }, numeric(1))
}

get.ttest.p.and.foldchange <- function(i, group1, group2) {
  p  <- t.test(i[group2], i[group1])$p.value
  fc <- mean(i[group2]) / mean(i[group1])
  return(c(fc, p))
}


### KEEP ONLY COLUMNS THAT APPEAR IN BOTH cfWGS & PON ##############################################
common_columns <- intersect(colnames(cfWGS.data), colnames(pon.data))
cfWGS.data      <- cfWGS.data[, common_columns, drop = FALSE]
pon.data        <- pon.data[, common_columns, drop = FALSE]


### 5.  LOOP OVER EACH SITE: COMPUTE METRICS + Z-SCORES + FC + THRESHOLDS  #####
### LOOP OVER EACH SITE: COMPUTE METRICS + Z-SCORES + T-TESTS #######################################
metrics.per.site <- list()
scores.per.site  <- list()

# stats.data for the dilution series is SIMPLIFIED relative to 1_7A:
# only Cohort-level fold-change and p-value columns are retained
# (Coverage.fc/p, Midpoint.fc/p, Amplitude.fc/p - tumour vs. healthy).
# The 1_7A columns PR.*, PS.*, response.p, and trial.p are omitted because
# there are no clinical subgroups (baseline / maintenance / trial arm)
# within the dilution series.
stats.data <- data.frame(
  Site            = unique(cfWGS.data[, c("site_name", "site_type")]     )$site_name,
  Type            = unique(cfWGS.data[, c("site_name", "site_type")]     )$site_type,
  Coverage.fc     = NA,  Midpoint.fc     = NA,  Amplitude.fc     = NA,
  Coverage.p      = NA,  Midpoint.p      = NA,  Amplitude.p      = NA,
  stringsAsFactors = FALSE
)

for (site in all.sites) {
  # combine cfWGS + PON rows for this site
  site.data <- rbind(
    cfWGS.data %>% filter(site_name == site),
    pon.data   %>% filter(site_name == site)
  )
  site.data <- as.data.table(site.data) %>% unique()
  
  # collapse duplicates and convert to data.table
  site.data <- site.data %>%
    group_by(Sample, site_name, site_type, Position, Cohort) %>%
    summarise(
      Coverage = mean(Coverage, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    as.data.table()
  
  # cast to wide format and convert to data.frame
  gc.distances <- data.table::dcast(
    site.data,
    Position ~ Sample,
    value.var = "Coverage"
  ) %>% as.data.frame()
  colnames(gc.distances) <- gsub("^Coverage\\.", "", colnames(gc.distances))
  
  # keep only valid samples in both places
  valid.samples <- intersect(colnames(gc.distances), all.samples)
  all.samples <- valid.samples
  
  # store this distance matrix
  metrics.per.site[[site]] <- data.frame(
    Sample            = valid.samples,
    Site              = rep(site, length(valid.samples)),
    fragmentomics_sequencing_platform = unname(sample_platform[valid.samples]),
    fragmentomics_sample_role = unname(sample_role[valid.samples]),
    Mean.Coverage     = colMeans(gc.distances[, valid.samples, drop = FALSE]),
    Midpoint.Coverage = colMeans(
      gc.distances[gc.distances$Position %in% c(-30, -15, 0, 15, 30), valid.samples, drop = FALSE]
    ),
    Midpoint.normalized = NA,
    Amplitude         = apply(GeneCycle::periodogram(gc.distances[, valid.samples, drop = FALSE])[["spec"]], 2, max)
  )
  
  # Midpoint.normalized = (Midpoint.Coverage - Mean.Coverage) + 1
  # Centres the near-dyad coverage on the global mean so that 1.0 = average
  # background; > 1.0 indicates elevated coverage at the site centre. This is a
  # difference shifted by 1, not a ratio or a universal accessibility direction.
  metrics.per.site[[site]]$Midpoint.normalized <-
    (metrics.per.site[[site]]$Midpoint.Coverage - metrics.per.site[[site]]$Mean.Coverage) + 1
  
  # Z-scores vs. PON: same formula as 1_7A - z = (x - mean_PON) / sd_PON.
  # Reference vector y is the subset of values belonging to pon.samples,
  # i.e. the TGL49 healthy-control bank, not the dilution series samples.
  metric_platform <- metrics.per.site[[site]]$fragmentomics_sequencing_platform
  metric_role <- metrics.per.site[[site]]$fragmentomics_sample_role
  score.data <- data.frame(
    Sample        = valid.samples,
    Site          = rep(site, length(valid.samples)),
    Zscore.Coverage =
      calculate_platform_zscores(metrics.per.site[[site]]$Mean.Coverage, metric_platform, metric_role),
    Zscore.Midpoint =
      calculate_platform_zscores(metrics.per.site[[site]]$Midpoint.normalized, metric_platform, metric_role),
    Zscore.Amplitude =
      calculate_platform_zscores(metrics.per.site[[site]]$Amplitude, metric_platform, metric_role)
  )
  scores.per.site[[site]] <- score.data
  
  # group comparisons (fold-change & p-value)
  mdata <- metrics.per.site[[site]]
  
  # tumour vs. healthy
  # Feature direction is frozen from the original NovaSeq 6000 dilution set.
  # XPlus validation dilutions are not allowed to redefine the direction.
  idx_pon <- which(mdata$fragmentomics_sample_role == "healthy_control" &
                     mdata$fragmentomics_sequencing_platform == "NovaSeq 6000")
  idx_tumor <- which(mdata$fragmentomics_sample_role == "dilution_series" &
                       mdata$fragmentomics_sequencing_platform == "NovaSeq 6000")
  stats.data[stats.data$Site == site, c("Coverage.fc", "Coverage.p")] <-
    get.ttest.p.and.foldchange(mdata$Mean.Coverage, idx_pon, idx_tumor)
  stats.data[stats.data$Site == site, c("Midpoint.fc", "Midpoint.p")] <-
    get.ttest.p.and.foldchange(mdata$Midpoint.normalized, idx_pon, idx_tumor)
  stats.data[stats.data$Site == site, c("Amplitude.fc", "Amplitude.p")] <-
    get.ttest.p.and.foldchange(mdata$Amplitude, idx_pon, idx_tumor)
  }

### 6.  ADJUST P-VALUES (FDR) #########################
### ADJUST P-VALUES (FDR) ############################################################################
fdr.data <- data.frame(
  Cohort.Cov.fdr   = p.adjust(stats.data$Coverage.p,    "fdr"),
  Cohort.Mid.fdr   = p.adjust(stats.data$Midpoint.p,    "fdr"),
  Cohort.Amp.fdr   = p.adjust(stats.data$Amplitude.p,   "fdr")
)


### 7.  COMBINE METRICS + SCORES + APPLY CLASSIFICATION FLAGS  #################
results.data <- merge(
  do.call(rbind, metrics.per.site),
  do.call(rbind, scores.per.site),
  all = TRUE
)

# Match the threshold reference to each sample's platform. Feature direction is
# retained from the original NovaSeq 6000 dilution series above.
threshold_lookup <- results.data %>%
  filter(.data$fragmentomics_sample_role == "healthy_control") %>%
  group_by(.data$Site, .data$fragmentomics_sequencing_platform) %>%
  summarise(
    Coverage.threshold.up = max(.data$Zscore.Coverage, na.rm = TRUE) * 1.10,
    Coverage.threshold.down = min(.data$Zscore.Coverage, na.rm = TRUE) * 1.10,
    Midpoint.threshold.up = max(.data$Zscore.Midpoint, na.rm = TRUE) * 1.10,
    Midpoint.threshold.down = min(.data$Zscore.Midpoint, na.rm = TRUE) * 1.10,
    Amplitude.threshold.up = max(.data$Zscore.Amplitude, na.rm = TRUE) * 1.10,
    Amplitude.threshold.down = min(.data$Zscore.Amplitude, na.rm = TRUE) * 1.10,
    n_healthy_reference = n_distinct(.data$Sample),
    .groups = "drop"
  ) %>%
  left_join(
    stats.data %>%
      dplyr::select(.data$Site, .data$Coverage.fc, .data$Midpoint.fc, .data$Amplitude.fc),
    by = "Site"
  ) %>%
  mutate(
    Coverage.threshold = if_else(.data$Coverage.fc > 1, .data$Coverage.threshold.up, .data$Coverage.threshold.down),
    Midpoint.threshold = if_else(.data$Midpoint.fc > 1, .data$Midpoint.threshold.up, .data$Midpoint.threshold.down),
    Amplitude.threshold = if_else(.data$Amplitude.fc > 1, .data$Amplitude.threshold.up, .data$Amplitude.threshold.down)
  )

stats.data <- stats.data %>%
  left_join(
    threshold_lookup %>%
      filter(.data$fragmentomics_sequencing_platform == "NovaSeq 6000") %>%
      dplyr::select(
        .data$Site, .data$Coverage.threshold,
        .data$Midpoint.threshold, .data$Amplitude.threshold
      ),
    by = "Site"
  )

write_csv(
  threshold_lookup,
  file.path(out.dir, "fragmentomics_platform_reference_thresholds_dilution.csv")
)

results.data <- results.data %>%
  dplyr::left_join(
    threshold_lookup %>%
      dplyr::select(
        .data$Site, .data$fragmentomics_sequencing_platform,
        .data$Coverage.fc, .data$Coverage.threshold,
        .data$Midpoint.fc, .data$Midpoint.threshold,
        .data$Amplitude.fc, .data$Amplitude.threshold,
        .data$n_healthy_reference
      ),
    by = c("Site", "fragmentomics_sequencing_platform")
  ) %>%
  dplyr::mutate(
    Threshold.Coverage = dplyr::case_when(
      is.na(Coverage.fc) | is.na(Coverage.threshold) ~ NA,
      Coverage.fc > 1 ~ Zscore.Coverage > Coverage.threshold,
      TRUE ~ Zscore.Coverage < Coverage.threshold
    ),
    Threshold.Midpoint = dplyr::case_when(
      is.na(Midpoint.fc) | is.na(Midpoint.threshold) ~ NA,
      Midpoint.fc > 1 ~ Zscore.Midpoint > Midpoint.threshold,
      TRUE ~ Zscore.Midpoint < Midpoint.threshold
    ),
    Threshold.Amplitude = dplyr::case_when(
      is.na(Amplitude.fc) | is.na(Amplitude.threshold) ~ NA,
      Amplitude.fc > 1 ~ Zscore.Amplitude > Amplitude.threshold,
      TRUE ~ Zscore.Amplitude < Amplitude.threshold
    )
  ) %>%
  dplyr::select(
    -Coverage.fc, -Coverage.threshold,
    -Midpoint.fc, -Midpoint.threshold,
    -Amplitude.fc, -Amplitude.threshold
  )

# Audit the corrected active direction rule against the historical rule. The
# legacy columns below reproduce fold-change > 0 for comparison only; they do
# not feed the dilution models or manuscript figures.
threshold_direction_sensitivity_audit <- results.data %>%
  left_join(
    threshold_lookup %>%
      select(
        Site, fragmentomics_sequencing_platform,
        Coverage.fc,
        Coverage.threshold.up, Coverage.threshold.down,
        Midpoint.fc,
        Midpoint.threshold.up, Midpoint.threshold.down,
        Amplitude.fc,
        Amplitude.threshold.up, Amplitude.threshold.down
      ),
    by = c("Site", "fragmentomics_sequencing_platform")
  ) %>%
  mutate(
    Threshold.Coverage.legacy = case_when(
      is.na(Coverage.fc) | is.na(Zscore.Coverage) ~ NA,
      Coverage.fc > 0 ~ Zscore.Coverage > Coverage.threshold.up,
      TRUE ~ Zscore.Coverage < Coverage.threshold.down
    ),
    Threshold.Midpoint.legacy = case_when(
      is.na(Midpoint.fc) | is.na(Zscore.Midpoint) ~ NA,
      Midpoint.fc > 0 ~ Zscore.Midpoint > Midpoint.threshold.up,
      TRUE ~ Zscore.Midpoint < Midpoint.threshold.down
    ),
    Threshold.Amplitude.legacy = case_when(
      is.na(Amplitude.fc) | is.na(Zscore.Amplitude) ~ NA,
      Amplitude.fc > 0 ~ Zscore.Amplitude > Amplitude.threshold.up,
      TRUE ~ Zscore.Amplitude < Amplitude.threshold.down
    ),
    Coverage.call_changed = Threshold.Coverage != Threshold.Coverage.legacy,
    Midpoint.call_changed = Threshold.Midpoint != Threshold.Midpoint.legacy,
    Amplitude.call_changed = Threshold.Amplitude != Threshold.Amplitude.legacy
  ) %>%
  filter(
    coalesce(Coverage.call_changed, FALSE) |
      coalesce(Midpoint.call_changed, FALSE) |
      coalesce(Amplitude.call_changed, FALSE)
  ) %>%
  select(
    Sample, Site,
    fragmentomics_sequencing_platform, fragmentomics_sample_role,
    starts_with("Zscore."),
    Coverage.fc, Coverage.threshold.up, Coverage.threshold.down,
    Threshold.Coverage.legacy, Threshold.Coverage,
    Coverage.call_changed,
    Midpoint.fc, Midpoint.threshold.up, Midpoint.threshold.down,
    Threshold.Midpoint.legacy, Threshold.Midpoint,
    Midpoint.call_changed,
    Amplitude.fc, Amplitude.threshold.up, Amplitude.threshold.down,
    Threshold.Amplitude.legacy, Threshold.Amplitude,
    Amplitude.call_changed
  )

write_csv(
  threshold_direction_sensitivity_audit,
  file.path(out.dir, "fragmentomics_threshold_direction_sensitivity_audit.csv")
)

# Save out per-site metrics + stats
dir.create(file.path(out.dir, "Griffin"), recursive = TRUE, showWarnings = FALSE)

write_tsv(results.data,
          file.path(out.dir, "Griffin/griffin_per_site_metrics_dilution.tsv"))

write_tsv(stats.data,
          file.path(out.dir, "Griffin/griffin_per_site_stats_dilution.tsv"))


### 8.  EXTRACT “MM_DARs_chromatin_activation” SITE + ATTACH CLINICAL KEYS ##########################
# Filter to the single MM-DAR site of interest, then re-attach columns from
# Metadata_dilution_series.csv. The historical `LOD` column stores the known
# prepared dilution percentage (input tumour-fraction level) for each library.
mm_dars_small <- results.data %>%
  filter(Site == "MM_DARs_chromatin_activation") %>%
  # re-attach Bam, Patient, Date_of_sample_collection from clinical.csv
  left_join(
    combined_clinical %>% 
      dplyr::select(Merge, Bam, Patient, Sample_ID, LOD),
    by = c("Sample" = "Merge")
  ) %>%
  dplyr::select(
    Sample, Site,
    Mean.Coverage, Midpoint.Coverage, Midpoint.normalized, Amplitude,
    Zscore.Coverage, Zscore.Midpoint, Zscore.Amplitude,
    Threshold.Coverage, Threshold.Midpoint, Threshold.Amplitude,
    fragmentomics_sequencing_platform, fragmentomics_sample_role,
    n_healthy_reference,
    Bam, Patient, Sample_ID, LOD
  ) %>%
  distinct()


### 9.  READ & MERGE INSERT-SIZE + FRAGMENT-SCORE (DILUTION) ###################
# 9a) INSERT-SIZE (“Proportion.Short”)
historical_ins_files <- list.files(
  path = ins_fs.dir,
  pattern = "insert_size_summary.tsv$",
  full.names = TRUE
)
xplus_ins_files <- spring2026_revision_files(
  "Fragmentomics_Pipeeline_Suite_all_outputs",
  "^2026-06-25_cfWGS_MM_fragmentomics_Revisions_Spring2026_PWGVAL_Dilution_series_insert_size_summary[.]tsv$"
)

read_summary_batch <- function(paths, platform) {
  if (!length(paths)) return(tibble())
  bind_rows(lapply(paths, function(path) {
    read_tsv(path, show_col_types = FALSE) %>%
      mutate(fragmentomics_sequencing_platform = platform)
  }))
}

insert_df <- bind_rows(
  read_summary_batch(historical_ins_files, "NovaSeq 6000"),
  read_summary_batch(xplus_ins_files, "NovaSeq XPlus")
) %>%
  mutate(Sample = clean_sample(Sample)) %>%
  dplyr::select(Sample, fragmentomics_sequencing_platform, Proportion.Short) %>%
  distinct()

# 9b) FRAGMENT SCORE (“FS”)
historical_fs_files <- list.files(
  path = ins_fs.dir,
  pattern = "fragment_scores.tsv$",
  full.names = TRUE
)
xplus_fs_files <- spring2026_revision_files(
  "Fragmentomics_Pipeeline_Suite_all_outputs",
  "^2026-06-25_cfWGS_MM_fragmentomics_Revisions_Spring2026_PWGVAL_Dilution_series_fragment_scores[.]tsv$"
)

fs_df <- bind_rows(
  read_summary_batch(historical_fs_files, "NovaSeq 6000"),
  read_summary_batch(xplus_fs_files, "NovaSeq XPlus")
) %>%
  mutate(Sample = clean_sample(Sample)) %>%
  dplyr::select(Sample, fragmentomics_sequencing_platform, FS) %>%
  distinct()


### 10. OPTIONAL: LOAD ADDITIONAL DILUTION METADATA  ######################################
if (file.exists(meta.csv)) {
  meta_df <- read_csv(meta.csv, show_col_types = FALSE)
  sample_key <- intersect(c("Sample", "Merge", "Sample_ID"), names(meta_df))[1]
  if (is.na(sample_key)) {
    stop("Dilution metadata must contain one of: Sample, Merge, Sample_ID. File: ", meta.csv)
  }
  meta_df <- meta_df %>%
    mutate(Sample = clean_sample(.data[[sample_key]]))
} else {
  meta_df <- tibble(Sample = character(0))
}


### 11. MERGE EVERYTHING INTO ONE “KEY” TABLE  ################################### Final output table assembles all three fragmentomics features per dilution
# sample in a single row:
#   • GRIFFIN MM-DARs metrics (Mean.Coverage, Midpoint.normalized, Amplitude,
#     Zscore.Coverage/Midpoint/Amplitude, Threshold flags)
#   • Proportion.Short   (short-fragment ratio from insert_size_summary.tsv)
#   • FS                 (CHARM Fragment Score from fragment_scores.tsv)
# Plus clinical keys: Bam, Patient, Sample_ID, and the historical `LOD` column
# containing the prepared dilution percentage. This table feeds directly into
# 3_1_part2 for the manuscript dilution-series sensitivity analysis.

key_frag_dilution <- mm_dars_small %>%
  dplyr::select(-Site) %>%
  # now join insert-size and FS
  left_join(insert_df, by = c("Sample", "fragmentomics_sequencing_platform")) %>%
  left_join(fs_df, by = c("Sample", "fragmentomics_sequencing_platform")) %>%
  # If any samples miss DARs entries (e.g. PON-only), they'll still appear with NA for DARs columns
  arrange(Sample)


## Remove healthy control info since already have in other table 
key_frag_dilution <- key_frag_dilution %>% filter(!is.na(Bam))

# Use the same healthy-control location/scale mapping as the main-cohort
# classifier. Z-scores above are already platform matched; only the raw frozen
# model predictors are mapped to the NovaSeq 6000 training scale.
harmonization_path <- file.path(
  "Results_Fragmentomics",
  "fragmentomics_platform_harmonization_reference_parameters.csv"
)
if (!file.exists(harmonization_path)) {
  stop(
    "Missing platform harmonization parameters. Run 1_7B before 1_7C: ",
    harmonization_path,
    call. = FALSE
  )
}
harmonization_reference <- read_csv(harmonization_path, show_col_types = FALSE)

harmonize_to_historical_scale <- function(data, feature, parameters) {
  historical <- parameters %>%
    filter(.data$feature == .env$feature, .data$fragmentomics_sequencing_platform == "NovaSeq 6000")
  xplus <- parameters %>%
    filter(.data$feature == .env$feature, .data$fragmentomics_sequencing_platform == "NovaSeq XPlus")
  if (nrow(historical) != 1L || nrow(xplus) != 1L ||
      !is.finite(historical$sd[[1]]) || !is.finite(xplus$sd[[1]]) || xplus$sd[[1]] <= 0) {
    stop("Invalid one-to-one harmonization parameters for feature: ", feature, call. = FALSE)
  }
  data[[paste0(feature, "_unharmonized")]] <- data[[feature]]
  idx <- data$fragmentomics_sequencing_platform == "NovaSeq XPlus" & is.finite(data[[feature]])
  data[[feature]][idx] <-
    ((data[[feature]][idx] - xplus$mean[[1]]) / xplus$sd[[1]]) * historical$sd[[1]] + historical$mean[[1]]
  data
}

for (feature in c("FS", "Proportion.Short", "Mean.Coverage")) {
  key_frag_dilution <- harmonize_to_historical_scale(
    key_frag_dilution,
    feature,
    harmonization_reference
  )
}

add_robust_harmonization <- function(data, feature, parameters) {
  historical <- parameters %>%
    filter(.data$feature == .env$feature, .data$fragmentomics_sequencing_platform == "NovaSeq 6000")
  xplus <- parameters %>%
    filter(.data$feature == .env$feature, .data$fragmentomics_sequencing_platform == "NovaSeq XPlus")
  if (nrow(historical) != 1L || nrow(xplus) != 1L ||
      !is.finite(historical$mad[[1]]) || !is.finite(xplus$mad[[1]]) || xplus$mad[[1]] <= 0) {
    stop("Invalid robust harmonization parameters for feature: ", feature, call. = FALSE)
  }
  raw_name <- paste0(feature, "_unharmonized")
  robust_name <- paste0(feature, "_harmonized_median_mad")
  data[[robust_name]] <- data[[raw_name]]
  idx <- data$fragmentomics_sequencing_platform == "NovaSeq XPlus" & is.finite(data[[raw_name]])
  data[[robust_name]][idx] <-
    ((data[[raw_name]][idx] - xplus$median[[1]]) / xplus$mad[[1]]) *
    historical$mad[[1]] + historical$median[[1]]
  data
}

for (feature in c("FS", "Proportion.Short", "Mean.Coverage")) {
  key_frag_dilution <- add_robust_harmonization(
    key_frag_dilution,
    feature,
    harmonization_reference
  )
}
key_frag_dilution <- key_frag_dilution %>%
  mutate(
    fragmentomics_harmonization_method = if_else(
      .data$fragmentomics_sequencing_platform == "NovaSeq XPlus",
      "XPlus healthy-control mean/SD mapped to NovaSeq 6000 healthy-control scale",
      "No transform; native NovaSeq 6000 scale"
    )
  )

# Fail loudly if the newly generated cases or historical dilution samples are
# assigned to the wrong platform.
new_case_rows <- key_frag_dilution %>% filter(str_detect(.data$Sample, "^VA-(09|12|13)-"))
if (!nrow(new_case_rows) || any(new_case_rows$fragmentomics_sequencing_platform != "NovaSeq XPlus")) {
  stop("VA-09, VA-12, and VA-13 dilution samples must all be labeled NovaSeq XPlus.", call. = FALSE)
}
historical_rows <- key_frag_dilution %>% filter(!str_detect(.data$Sample, "^VA-(09|12|13)-"))
if (nrow(historical_rows) && any(historical_rows$fragmentomics_sequencing_platform != "NovaSeq 6000")) {
  stop("Historical dilution samples must all be labeled NovaSeq 6000.", call. = FALSE)
}

write_csv(
  key_frag_dilution %>%
    dplyr::select(
      Sample, Patient, Sample_ID, LOD,
      fragmentomics_sequencing_platform, fragmentomics_harmonization_method,
      FS_unharmonized, FS,
      FS_harmonized_median_mad,
      Proportion.Short_unharmonized, Proportion.Short,
      Proportion.Short_harmonized_median_mad,
      Mean.Coverage_unharmonized, Mean.Coverage,
      Mean.Coverage_harmonized_median_mad,
      Zscore.Coverage, Zscore.Midpoint, Zscore.Amplitude,
      n_healthy_reference
    ),
  file.path(out.dir, "fragmentomics_platform_harmonization_dilution_audit.csv")
)

### 12. WRITE OUT FINAL CSV & RDS  #############################################
write_csv(
  key_frag_dilution,
  file = file.path(out.dir, "key_fragmentomics_info_dilution_series.csv")
)

write_rds(
  key_frag_dilution,
  file = file.path(out.dir, "key_fragmentomics_info_dilution_series.rds")
)


message("✔️  Done! Wrote: ", 
        file.path(out.dir, "key_fragmentomics_info_dilution_series.csv"))
